// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: obd2_gauge_catalyst

#ifndef _OBD2_GAUGE_CATALYST_UI_H
#define _OBD2_GAUGE_CATALYST_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////
#include "ui_Screen_ScreenTitle.h"
#include "ui_Screen_ScreenGauge.h"
#include "ui_Screen_ScreenMonitor.h"
#include "ui_Screen_ScreenConfig.h"
#include "ui_Screen_ScreenService.h"
#include "ui_Screen_ScreenPerformance.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
extern lv_obj_t *ui_Startevents____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE( ui_img_vaandcob_png);   // assets/vaandcob.png
LV_IMG_DECLARE( ui_img_gauge3_png);   // assets/gauge3.png
LV_IMG_DECLARE( ui_img_ledring_png);   // assets/ledring.png
LV_IMG_DECLARE( ui_img_moon_png);   // assets/moon.png
LV_IMG_DECLARE( ui_img_sun_png);   // assets/sun.png
LV_IMG_DECLARE( ui_img_thailand_png);   // assets/thailand.png
LV_IMG_DECLARE( ui_img_qrcode_png);   // assets/qrcode.png
LV_IMG_DECLARE( ui_img_mil_png);   // assets/mil.png
LV_IMG_DECLARE( ui_img_alert_png);   // assets/alert.png

// FONTS
LV_FONT_DECLARE( ui_font_oswald_36);
LV_FONT_DECLARE( ui_font_segment_40);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
