// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: obd2_gauge_catalyst

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void sweepDial(lv_event_t * e);
void changeScreenConfig(lv_event_t * e);
void changeScreenMonitor(lv_event_t * e);
void changeScreenService(lv_event_t * e);
void changeScreenPerformance(lv_event_t * e);
void changeScreenGauge(lv_event_t * e);
void setupTabChanged(lv_event_t * e);
void setBrightness(lv_event_t * e);
void setVolume(lv_event_t * e);
void autoPowerOffEnable(lv_event_t * e);
void autoPowerOffDisable(lv_event_t * e);
void showSystemInfo(lv_event_t * e);
void hideSystemInfo(lv_event_t * e);
void loadCustomPid(lv_event_t * e);
void saveConfig(lv_event_t * e);
void changeFont(lv_event_t * e);
void activate(lv_event_t * e);
void readKeyboard(lv_event_t * e);
void serviceTabChanged(lv_event_t * e);
void loadWarning(lv_event_t * e);
void setWarningLimit(lv_event_t * e);
void readDTC(lv_event_t * e);
void updateDTC(lv_event_t * e);
void confirmClearMIL(lv_event_t * e);
void abortClearMIL(lv_event_t * e);
void togglePointChart1(lv_event_t * e);
void togglePointChart2(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
