// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: obd2_gauge_catalyst

#ifndef UI_SCREEN_SCREENPERFORMANCE_H
#define UI_SCREEN_SCREENPERFORMANCE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen_ScreenPerformance
extern void ui_Screen_ScreenPerformance_screen_init(void);
extern void ui_Screen_ScreenPerformance_screen_destroy(void);
extern void ui_event_Screen_ScreenPerformance( lv_event_t * e);
extern lv_obj_t *ui_Screen_ScreenPerformance;
extern void ui_event_ScreenPerformance_Chart_top( lv_event_t * e);
extern lv_obj_t *ui_ScreenPerformance_Chart_top;
extern lv_obj_t *ui_ScreenPerformance_Label_series1left;
extern lv_obj_t *ui_ScreenPerformance_Label_series1right;
extern lv_obj_t *ui_ScreenPerformance_Label_chart1X;
extern void ui_event_ScreenPerformance_Chart_bottom( lv_event_t * e);
extern lv_obj_t *ui_ScreenPerformance_Chart_bottom;
extern lv_obj_t *ui_ScreenPerformance_Label_series2left;
extern lv_obj_t *ui_ScreenPerformance_Label_series2right;
extern lv_obj_t *ui_ScreenPerformance_Label_chart2X;
extern void ui_event_ScreenPerformance_Button_swipeRight( lv_event_t * e);
extern lv_obj_t *ui_ScreenPerformance_Button_swipeRight;
extern lv_obj_t *ui_ScreenPerformance_Label_right;
extern lv_obj_t *ui_ScreenPerformance_Label_info3;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

