// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: obd2_gauge_catalyst

#include "ui.h"

lv_obj_t *ui_Screen_ScreenGauge = NULL;lv_obj_t *ui_ScreenGauge_Container_Container1 = NULL;lv_obj_t *ui_ScreenGauge_Label_number1 = NULL;lv_obj_t *ui_ScreenGauge_Label_pid1 = NULL;lv_obj_t *ui_ScreenGauge_Label_unit1 = NULL;lv_obj_t *ui_ScreenGauge_Container_Container2 = NULL;lv_obj_t *ui_ScreenGauge_Label_number2 = NULL;lv_obj_t *ui_ScreenGauge_Label_pid2 = NULL;lv_obj_t *ui_ScreenGauge_Label_unit2 = NULL;lv_obj_t *ui_ScreenGauge_Container_Container3 = NULL;lv_obj_t *ui_ScreenGauge_Label_number3 = NULL;lv_obj_t *ui_ScreenGauge_Label_pid3 = NULL;lv_obj_t *ui_ScreenGauge_Label_unit3 = NULL;lv_obj_t *ui_ScreenGauge_Container_Container4 = NULL;lv_obj_t *ui_ScreenGauge_Label_number4 = NULL;lv_obj_t *ui_ScreenGauge_Label_pid4 = NULL;lv_obj_t *ui_ScreenGauge_Label_unit4 = NULL;lv_obj_t *ui_ScreenGauge_Container_Container5 = NULL;lv_obj_t *ui_ScreenGauge_Label_number5 = NULL;lv_obj_t *ui_ScreenGauge_Label_pid5 = NULL;lv_obj_t *ui_ScreenGauge_Label_unit5 = NULL;lv_obj_t *ui_ScreenGauge_Container_Container6 = NULL;lv_obj_t *ui_ScreenGauge_Label_number6 = NULL;lv_obj_t *ui_ScreenGauge_Label_pid6 = NULL;lv_obj_t *ui_ScreenGauge_Label_unit6 = NULL;lv_obj_t *ui_ScreenGauge_Container_container7 = NULL;lv_obj_t *ui_ScreenGauge_Label_number7 = NULL;lv_obj_t *ui_ScreenGauge_Label_pid7 = NULL;lv_obj_t *ui_ScreenGauge_Label_unit7 = NULL;lv_obj_t *ui_ScreenGauge_Container_container8 = NULL;lv_obj_t *ui_ScreenGauge_Label_info1 = NULL;lv_obj_t *ui_ScreenGauge_Container_roundgauge = NULL;lv_obj_t *ui_ScreenGauge_Arc_rpm = NULL;lv_obj_t *ui_ScreenGauge_Label_speed = NULL;lv_obj_t *ui_ScreenGauge_Label_gear = NULL;lv_obj_t *ui_ScreenGauge_Label_RPMx1000 = NULL;lv_obj_t *ui_ScreenGauge_Label_kmh = NULL;
// event funtions
void ui_event_Screen_ScreenGauge( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_BOTTOM  ) {
lv_indev_wait_release(lv_indev_get_act());
      _ui_screen_change( &ui_Screen_ScreenConfig, LV_SCR_LOAD_ANIM_MOVE_BOTTOM, 500, 0, &ui_Screen_ScreenConfig_screen_init);
      changeScreenConfig( e );
}
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT  ) {
lv_indev_wait_release(lv_indev_get_act());
      _ui_screen_change( &ui_Screen_ScreenMonitor, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_Screen_ScreenMonitor_screen_init);
      changeScreenMonitor( e );
}
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_TOP  ) {
lv_indev_wait_release(lv_indev_get_act());
      _ui_screen_change( &ui_Screen_ScreenService, LV_SCR_LOAD_ANIM_MOVE_TOP, 500, 0, &ui_Screen_ScreenService_screen_init);
      changeScreenService( e );
}
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT  ) {
lv_indev_wait_release(lv_indev_get_act());
      changeScreenPerformance( e );
      _ui_screen_change( &ui_Screen_ScreenPerformance, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_Screen_ScreenPerformance_screen_init);
}
}

// build funtions

void ui_Screen_ScreenGauge_screen_init(void)
{
ui_Screen_ScreenGauge = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen_ScreenGauge, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Screen_ScreenGauge, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Screen_ScreenGauge, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_Screen_ScreenGauge, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Screen_ScreenGauge, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Screen_ScreenGauge, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Screen_ScreenGauge, &ui_font_oswald_36, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_Screen_ScreenGauge, lv_color_hex(0x000000), LV_PART_SCROLLBAR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Screen_ScreenGauge, 255, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);

ui_ScreenGauge_Container_Container1 = lv_obj_create(ui_Screen_ScreenGauge);
lv_obj_remove_style_all(ui_ScreenGauge_Container_Container1);
lv_obj_set_width( ui_ScreenGauge_Container_Container1, 80);
lv_obj_set_height( ui_ScreenGauge_Container_Container1, 80);
lv_obj_clear_flag( ui_ScreenGauge_Container_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_bg_color(ui_ScreenGauge_Container_Container1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ScreenGauge_Container_Container1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_ScreenGauge_Container_Container1, lv_color_hex(0x7F0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_main_stop(ui_ScreenGauge_Container_Container1, 120, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_stop(ui_ScreenGauge_Container_Container1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_dir(ui_ScreenGauge_Container_Container1, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_ScreenGauge_Container_Container1, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_ScreenGauge_Container_Container1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_ScreenGauge_Container_Container1, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_ScreenGauge_Container_Container1, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ScreenGauge_Label_number1 = lv_label_create(ui_ScreenGauge_Container_Container1);
lv_obj_set_width( ui_ScreenGauge_Label_number1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ScreenGauge_Label_number1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ScreenGauge_Label_number1, 0 );
lv_obj_set_y( ui_ScreenGauge_Label_number1, 8 );
lv_obj_set_align( ui_ScreenGauge_Label_number1, LV_ALIGN_CENTER );
lv_label_set_text(ui_ScreenGauge_Label_number1,"0");
lv_obj_set_style_text_color(ui_ScreenGauge_Label_number1, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ScreenGauge_Label_number1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ScreenGauge_Label_pid1 = lv_label_create(ui_ScreenGauge_Container_Container1);
lv_obj_set_width( ui_ScreenGauge_Label_pid1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ScreenGauge_Label_pid1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_ScreenGauge_Label_pid1, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_ScreenGauge_Label_pid1,"-");
lv_obj_set_style_text_align(ui_ScreenGauge_Label_pid1, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_ScreenGauge_Label_pid1, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ScreenGauge_Label_unit1 = lv_label_create(ui_ScreenGauge_Container_Container1);
lv_obj_set_width( ui_ScreenGauge_Label_unit1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ScreenGauge_Label_unit1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_ScreenGauge_Label_unit1, LV_ALIGN_BOTTOM_MID );
lv_label_set_text(ui_ScreenGauge_Label_unit1,"-");
lv_obj_set_style_text_color(ui_ScreenGauge_Label_unit1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ScreenGauge_Label_unit1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_ScreenGauge_Label_unit1, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ScreenGauge_Container_Container2 = lv_obj_create(ui_Screen_ScreenGauge);
lv_obj_remove_style_all(ui_ScreenGauge_Container_Container2);
lv_obj_set_width( ui_ScreenGauge_Container_Container2, 80);
lv_obj_set_height( ui_ScreenGauge_Container_Container2, 80);
lv_obj_set_align( ui_ScreenGauge_Container_Container2, LV_ALIGN_LEFT_MID );
lv_obj_clear_flag( ui_ScreenGauge_Container_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_bg_color(ui_ScreenGauge_Container_Container2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ScreenGauge_Container_Container2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_ScreenGauge_Container_Container2, lv_color_hex(0x7F0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_main_stop(ui_ScreenGauge_Container_Container2, 120, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_stop(ui_ScreenGauge_Container_Container2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_dir(ui_ScreenGauge_Container_Container2, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_ScreenGauge_Container_Container2, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_ScreenGauge_Container_Container2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_ScreenGauge_Container_Container2, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_ScreenGauge_Container_Container2, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ScreenGauge_Label_number2 = lv_label_create(ui_ScreenGauge_Container_Container2);
lv_obj_set_width( ui_ScreenGauge_Label_number2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ScreenGauge_Label_number2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ScreenGauge_Label_number2, 0 );
lv_obj_set_y( ui_ScreenGauge_Label_number2, 5 );
lv_obj_set_align( ui_ScreenGauge_Label_number2, LV_ALIGN_CENTER );
lv_label_set_text(ui_ScreenGauge_Label_number2,"0");
lv_obj_set_style_text_color(ui_ScreenGauge_Label_number2, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ScreenGauge_Label_number2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ScreenGauge_Label_pid2 = lv_label_create(ui_ScreenGauge_Container_Container2);
lv_obj_set_width( ui_ScreenGauge_Label_pid2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ScreenGauge_Label_pid2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_ScreenGauge_Label_pid2, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_ScreenGauge_Label_pid2,"-");
lv_obj_set_style_text_align(ui_ScreenGauge_Label_pid2, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_ScreenGauge_Label_pid2, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ScreenGauge_Label_unit2 = lv_label_create(ui_ScreenGauge_Container_Container2);
lv_obj_set_width( ui_ScreenGauge_Label_unit2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ScreenGauge_Label_unit2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_ScreenGauge_Label_unit2, LV_ALIGN_BOTTOM_MID );
lv_label_set_text(ui_ScreenGauge_Label_unit2,"-");
lv_obj_set_style_text_color(ui_ScreenGauge_Label_unit2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ScreenGauge_Label_unit2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_ScreenGauge_Label_unit2, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ScreenGauge_Container_Container3 = lv_obj_create(ui_Screen_ScreenGauge);
lv_obj_remove_style_all(ui_ScreenGauge_Container_Container3);
lv_obj_set_width( ui_ScreenGauge_Container_Container3, 80);
lv_obj_set_height( ui_ScreenGauge_Container_Container3, 80);
lv_obj_set_align( ui_ScreenGauge_Container_Container3, LV_ALIGN_BOTTOM_LEFT );
lv_obj_clear_flag( ui_ScreenGauge_Container_Container3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_bg_color(ui_ScreenGauge_Container_Container3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ScreenGauge_Container_Container3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_ScreenGauge_Container_Container3, lv_color_hex(0x7F0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_main_stop(ui_ScreenGauge_Container_Container3, 120, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_stop(ui_ScreenGauge_Container_Container3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_dir(ui_ScreenGauge_Container_Container3, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_ScreenGauge_Container_Container3, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_ScreenGauge_Container_Container3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_ScreenGauge_Container_Container3, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_ScreenGauge_Container_Container3, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ScreenGauge_Label_number3 = lv_label_create(ui_ScreenGauge_Container_Container3);
lv_obj_set_width( ui_ScreenGauge_Label_number3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ScreenGauge_Label_number3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ScreenGauge_Label_number3, 0 );
lv_obj_set_y( ui_ScreenGauge_Label_number3, 8 );
lv_obj_set_align( ui_ScreenGauge_Label_number3, LV_ALIGN_CENTER );
lv_label_set_text(ui_ScreenGauge_Label_number3,"0");
lv_obj_set_style_text_color(ui_ScreenGauge_Label_number3, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ScreenGauge_Label_number3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ScreenGauge_Label_pid3 = lv_label_create(ui_ScreenGauge_Container_Container3);
lv_obj_set_width( ui_ScreenGauge_Label_pid3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ScreenGauge_Label_pid3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_ScreenGauge_Label_pid3, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_ScreenGauge_Label_pid3,"-");
lv_obj_set_style_text_align(ui_ScreenGauge_Label_pid3, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_ScreenGauge_Label_pid3, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ScreenGauge_Label_unit3 = lv_label_create(ui_ScreenGauge_Container_Container3);
lv_obj_set_width( ui_ScreenGauge_Label_unit3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ScreenGauge_Label_unit3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_ScreenGauge_Label_unit3, LV_ALIGN_BOTTOM_MID );
lv_label_set_text(ui_ScreenGauge_Label_unit3,"-");
lv_obj_set_style_text_color(ui_ScreenGauge_Label_unit3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ScreenGauge_Label_unit3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_ScreenGauge_Label_unit3, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ScreenGauge_Container_Container4 = lv_obj_create(ui_Screen_ScreenGauge);
lv_obj_remove_style_all(ui_ScreenGauge_Container_Container4);
lv_obj_set_width( ui_ScreenGauge_Container_Container4, 80);
lv_obj_set_height( ui_ScreenGauge_Container_Container4, 80);
lv_obj_set_align( ui_ScreenGauge_Container_Container4, LV_ALIGN_TOP_RIGHT );
lv_obj_clear_flag( ui_ScreenGauge_Container_Container4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_bg_color(ui_ScreenGauge_Container_Container4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ScreenGauge_Container_Container4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_ScreenGauge_Container_Container4, lv_color_hex(0x7F0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_main_stop(ui_ScreenGauge_Container_Container4, 120, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_stop(ui_ScreenGauge_Container_Container4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_dir(ui_ScreenGauge_Container_Container4, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_ScreenGauge_Container_Container4, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_ScreenGauge_Container_Container4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_ScreenGauge_Container_Container4, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_ScreenGauge_Container_Container4, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ScreenGauge_Label_number4 = lv_label_create(ui_ScreenGauge_Container_Container4);
lv_obj_set_width( ui_ScreenGauge_Label_number4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ScreenGauge_Label_number4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ScreenGauge_Label_number4, 0 );
lv_obj_set_y( ui_ScreenGauge_Label_number4, 8 );
lv_obj_set_align( ui_ScreenGauge_Label_number4, LV_ALIGN_CENTER );
lv_label_set_text(ui_ScreenGauge_Label_number4,"0");
lv_obj_set_style_text_color(ui_ScreenGauge_Label_number4, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ScreenGauge_Label_number4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ScreenGauge_Label_pid4 = lv_label_create(ui_ScreenGauge_Container_Container4);
lv_obj_set_width( ui_ScreenGauge_Label_pid4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ScreenGauge_Label_pid4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_ScreenGauge_Label_pid4, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_ScreenGauge_Label_pid4,"-");
lv_obj_set_style_text_align(ui_ScreenGauge_Label_pid4, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_ScreenGauge_Label_pid4, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ScreenGauge_Label_unit4 = lv_label_create(ui_ScreenGauge_Container_Container4);
lv_obj_set_width( ui_ScreenGauge_Label_unit4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ScreenGauge_Label_unit4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_ScreenGauge_Label_unit4, LV_ALIGN_BOTTOM_MID );
lv_label_set_text(ui_ScreenGauge_Label_unit4,"-");
lv_obj_set_style_text_color(ui_ScreenGauge_Label_unit4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ScreenGauge_Label_unit4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_ScreenGauge_Label_unit4, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ScreenGauge_Container_Container5 = lv_obj_create(ui_Screen_ScreenGauge);
lv_obj_remove_style_all(ui_ScreenGauge_Container_Container5);
lv_obj_set_width( ui_ScreenGauge_Container_Container5, 80);
lv_obj_set_height( ui_ScreenGauge_Container_Container5, 80);
lv_obj_set_align( ui_ScreenGauge_Container_Container5, LV_ALIGN_RIGHT_MID );
lv_obj_clear_flag( ui_ScreenGauge_Container_Container5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_bg_color(ui_ScreenGauge_Container_Container5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ScreenGauge_Container_Container5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_ScreenGauge_Container_Container5, lv_color_hex(0x7F0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_main_stop(ui_ScreenGauge_Container_Container5, 120, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_stop(ui_ScreenGauge_Container_Container5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_dir(ui_ScreenGauge_Container_Container5, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_ScreenGauge_Container_Container5, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_ScreenGauge_Container_Container5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_ScreenGauge_Container_Container5, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_ScreenGauge_Container_Container5, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ScreenGauge_Label_number5 = lv_label_create(ui_ScreenGauge_Container_Container5);
lv_obj_set_width( ui_ScreenGauge_Label_number5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ScreenGauge_Label_number5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ScreenGauge_Label_number5, 0 );
lv_obj_set_y( ui_ScreenGauge_Label_number5, 8 );
lv_obj_set_align( ui_ScreenGauge_Label_number5, LV_ALIGN_CENTER );
lv_label_set_text(ui_ScreenGauge_Label_number5,"0");
lv_obj_set_style_text_color(ui_ScreenGauge_Label_number5, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ScreenGauge_Label_number5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ScreenGauge_Label_pid5 = lv_label_create(ui_ScreenGauge_Container_Container5);
lv_obj_set_width( ui_ScreenGauge_Label_pid5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ScreenGauge_Label_pid5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_ScreenGauge_Label_pid5, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_ScreenGauge_Label_pid5,"-");
lv_obj_set_style_text_align(ui_ScreenGauge_Label_pid5, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_ScreenGauge_Label_pid5, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ScreenGauge_Label_unit5 = lv_label_create(ui_ScreenGauge_Container_Container5);
lv_obj_set_width( ui_ScreenGauge_Label_unit5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ScreenGauge_Label_unit5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_ScreenGauge_Label_unit5, LV_ALIGN_BOTTOM_MID );
lv_label_set_text(ui_ScreenGauge_Label_unit5,"-");
lv_obj_set_style_text_color(ui_ScreenGauge_Label_unit5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ScreenGauge_Label_unit5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_ScreenGauge_Label_unit5, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ScreenGauge_Container_Container6 = lv_obj_create(ui_Screen_ScreenGauge);
lv_obj_remove_style_all(ui_ScreenGauge_Container_Container6);
lv_obj_set_width( ui_ScreenGauge_Container_Container6, 80);
lv_obj_set_height( ui_ScreenGauge_Container_Container6, 80);
lv_obj_set_align( ui_ScreenGauge_Container_Container6, LV_ALIGN_BOTTOM_RIGHT );
lv_obj_clear_flag( ui_ScreenGauge_Container_Container6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_bg_color(ui_ScreenGauge_Container_Container6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ScreenGauge_Container_Container6, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_ScreenGauge_Container_Container6, lv_color_hex(0x7F0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_main_stop(ui_ScreenGauge_Container_Container6, 120, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_stop(ui_ScreenGauge_Container_Container6, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_dir(ui_ScreenGauge_Container_Container6, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_ScreenGauge_Container_Container6, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_ScreenGauge_Container_Container6, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_ScreenGauge_Container_Container6, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_ScreenGauge_Container_Container6, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ScreenGauge_Label_number6 = lv_label_create(ui_ScreenGauge_Container_Container6);
lv_obj_set_width( ui_ScreenGauge_Label_number6, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ScreenGauge_Label_number6, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ScreenGauge_Label_number6, 0 );
lv_obj_set_y( ui_ScreenGauge_Label_number6, 8 );
lv_obj_set_align( ui_ScreenGauge_Label_number6, LV_ALIGN_CENTER );
lv_label_set_text(ui_ScreenGauge_Label_number6,"0");
lv_obj_set_style_text_color(ui_ScreenGauge_Label_number6, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ScreenGauge_Label_number6, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ScreenGauge_Label_pid6 = lv_label_create(ui_ScreenGauge_Container_Container6);
lv_obj_set_width( ui_ScreenGauge_Label_pid6, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ScreenGauge_Label_pid6, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_ScreenGauge_Label_pid6, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_ScreenGauge_Label_pid6,"-");
lv_obj_set_style_text_align(ui_ScreenGauge_Label_pid6, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_ScreenGauge_Label_pid6, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ScreenGauge_Label_unit6 = lv_label_create(ui_ScreenGauge_Container_Container6);
lv_obj_set_width( ui_ScreenGauge_Label_unit6, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ScreenGauge_Label_unit6, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_ScreenGauge_Label_unit6, LV_ALIGN_BOTTOM_MID );
lv_label_set_text(ui_ScreenGauge_Label_unit6,"-");
lv_obj_set_style_text_color(ui_ScreenGauge_Label_unit6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ScreenGauge_Label_unit6, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_ScreenGauge_Label_unit6, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ScreenGauge_Container_container7 = lv_obj_create(ui_Screen_ScreenGauge);
lv_obj_remove_style_all(ui_ScreenGauge_Container_container7);
lv_obj_set_width( ui_ScreenGauge_Container_container7, 150);
lv_obj_set_height( ui_ScreenGauge_Container_container7, 54);
lv_obj_set_align( ui_ScreenGauge_Container_container7, LV_ALIGN_BOTTOM_MID );
lv_obj_clear_flag( ui_ScreenGauge_Container_container7, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_radius(ui_ScreenGauge_Container_container7, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_ScreenGauge_Container_container7, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ScreenGauge_Container_container7, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_ScreenGauge_Container_container7, lv_color_hex(0x7F0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_main_stop(ui_ScreenGauge_Container_container7, 150, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_stop(ui_ScreenGauge_Container_container7, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_dir(ui_ScreenGauge_Container_container7, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_ScreenGauge_Container_container7, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_ScreenGauge_Container_container7, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_ScreenGauge_Container_container7, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_ScreenGauge_Container_container7, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_ScreenGauge_Container_container7, lv_color_hex(0x222222), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_ScreenGauge_Container_container7, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_width(ui_ScreenGauge_Container_container7, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_pad(ui_ScreenGauge_Container_container7, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_ScreenGauge_Container_container7, lv_color_hex(0x666666), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_ScreenGauge_Container_container7, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_ScreenGauge_Container_container7, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_ScreenGauge_Container_container7, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ScreenGauge_Label_number7 = lv_label_create(ui_ScreenGauge_Container_container7);
lv_obj_set_width( ui_ScreenGauge_Label_number7, LV_SIZE_CONTENT);  /// 90
lv_obj_set_height( ui_ScreenGauge_Label_number7, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ScreenGauge_Label_number7, 0 );
lv_obj_set_y( ui_ScreenGauge_Label_number7, 7 );
lv_obj_set_align( ui_ScreenGauge_Label_number7, LV_ALIGN_CENTER );
lv_label_set_text(ui_ScreenGauge_Label_number7,"0");
lv_obj_set_style_text_color(ui_ScreenGauge_Label_number7, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ScreenGauge_Label_number7, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_ScreenGauge_Label_number7, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ScreenGauge_Label_pid7 = lv_label_create(ui_ScreenGauge_Container_container7);
lv_obj_set_width( ui_ScreenGauge_Label_pid7, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ScreenGauge_Label_pid7, LV_SIZE_CONTENT);   /// 1
lv_label_set_text(ui_ScreenGauge_Label_pid7,"-");
lv_obj_set_style_text_align(ui_ScreenGauge_Label_pid7, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_ScreenGauge_Label_pid7, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ScreenGauge_Label_unit7 = lv_label_create(ui_ScreenGauge_Container_container7);
lv_obj_set_width( ui_ScreenGauge_Label_unit7, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ScreenGauge_Label_unit7, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ScreenGauge_Label_unit7, 0 );
lv_obj_set_y( ui_ScreenGauge_Label_unit7, -4 );
lv_obj_set_align( ui_ScreenGauge_Label_unit7, LV_ALIGN_BOTTOM_RIGHT );
lv_label_set_text(ui_ScreenGauge_Label_unit7,"-");
lv_obj_set_style_text_color(ui_ScreenGauge_Label_unit7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ScreenGauge_Label_unit7, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_ScreenGauge_Label_unit7, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_ScreenGauge_Label_unit7, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ScreenGauge_Container_container8 = lv_obj_create(ui_Screen_ScreenGauge);
lv_obj_remove_style_all(ui_ScreenGauge_Container_container8);
lv_obj_set_width( ui_ScreenGauge_Container_container8, 150);
lv_obj_set_height( ui_ScreenGauge_Container_container8, 54);
lv_obj_set_align( ui_ScreenGauge_Container_container8, LV_ALIGN_TOP_MID );
lv_obj_clear_flag( ui_ScreenGauge_Container_container8, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_radius(ui_ScreenGauge_Container_container8, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_ScreenGauge_Container_container8, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ScreenGauge_Container_container8, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_ScreenGauge_Container_container8, lv_color_hex(0x7F0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_main_stop(ui_ScreenGauge_Container_container8, 150, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_stop(ui_ScreenGauge_Container_container8, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_dir(ui_ScreenGauge_Container_container8, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_ScreenGauge_Container_container8, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_ScreenGauge_Container_container8, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_ScreenGauge_Container_container8, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_ScreenGauge_Container_container8, LV_BORDER_SIDE_TOP, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_ScreenGauge_Container_container8, lv_color_hex(0x222222), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_ScreenGauge_Container_container8, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_width(ui_ScreenGauge_Container_container8, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_pad(ui_ScreenGauge_Container_container8, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_ScreenGauge_Container_container8, lv_color_hex(0x666666), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_ScreenGauge_Container_container8, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_ScreenGauge_Container_container8, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_ScreenGauge_Container_container8, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ScreenGauge_Label_info1 = lv_label_create(ui_ScreenGauge_Container_container8);
lv_obj_set_width( ui_ScreenGauge_Label_info1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ScreenGauge_Label_info1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ScreenGauge_Label_info1, 0 );
lv_obj_set_y( ui_ScreenGauge_Label_info1, 3 );
lv_obj_set_align( ui_ScreenGauge_Label_info1, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_ScreenGauge_Label_info1,"- Catalyst -");
lv_obj_set_style_text_color(ui_ScreenGauge_Label_info1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ScreenGauge_Label_info1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_ScreenGauge_Label_info1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_ScreenGauge_Label_info1, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_ScreenGauge_Label_info1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ScreenGauge_Label_info1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ScreenGauge_Container_roundgauge = lv_obj_create(ui_Screen_ScreenGauge);
lv_obj_remove_style_all(ui_ScreenGauge_Container_roundgauge);
lv_obj_set_width( ui_ScreenGauge_Container_roundgauge, 160);
lv_obj_set_height( ui_ScreenGauge_Container_roundgauge, 160);
lv_obj_set_align( ui_ScreenGauge_Container_roundgauge, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_ScreenGauge_Container_roundgauge, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_bg_img_src( ui_ScreenGauge_Container_roundgauge, &ui_img_gauge3_png, LV_PART_MAIN | LV_STATE_DEFAULT );

ui_ScreenGauge_Arc_rpm = lv_arc_create(ui_ScreenGauge_Container_roundgauge);
lv_obj_set_width( ui_ScreenGauge_Arc_rpm, 140);
lv_obj_set_height( ui_ScreenGauge_Arc_rpm, 151);
lv_obj_set_x( ui_ScreenGauge_Arc_rpm, -1 );
lv_obj_set_y( ui_ScreenGauge_Arc_rpm, 6 );
lv_obj_set_align( ui_ScreenGauge_Arc_rpm, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_ScreenGauge_Arc_rpm, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_arc_set_range(ui_ScreenGauge_Arc_rpm, 0,80);
lv_arc_set_value(ui_ScreenGauge_Arc_rpm, 0);
lv_arc_set_bg_angles(ui_ScreenGauge_Arc_rpm,150,30);
lv_obj_set_style_pad_left(ui_ScreenGauge_Arc_rpm, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_ScreenGauge_Arc_rpm, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_ScreenGauge_Arc_rpm, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_ScreenGauge_Arc_rpm, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_color(ui_ScreenGauge_Arc_rpm, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_ScreenGauge_Arc_rpm, 45, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_img_src( ui_ScreenGauge_Arc_rpm, &ui_img_ledring_png, LV_PART_MAIN | LV_STATE_DEFAULT );

lv_obj_set_style_border_width(ui_ScreenGauge_Arc_rpm, 5, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_ScreenGauge_Arc_rpm, LV_BORDER_SIDE_FULL, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_blend_mode(ui_ScreenGauge_Arc_rpm, LV_BLEND_MODE_ADDITIVE, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_ScreenGauge_Arc_rpm, 3, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_ScreenGauge_Arc_rpm, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_ScreenGauge_Arc_rpm, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_ScreenGauge_Arc_rpm, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_ScreenGauge_Arc_rpm, 8, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_rounded(ui_ScreenGauge_Arc_rpm, false, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_img_src( ui_ScreenGauge_Arc_rpm, &ui_img_ledring_png, LV_PART_INDICATOR | LV_STATE_DEFAULT );

lv_obj_set_style_bg_color(ui_ScreenGauge_Arc_rpm, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ScreenGauge_Arc_rpm, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_ScreenGauge_Label_speed = lv_label_create(ui_ScreenGauge_Container_roundgauge);
lv_obj_set_width( ui_ScreenGauge_Label_speed, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ScreenGauge_Label_speed, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ScreenGauge_Label_speed, 0 );
lv_obj_set_y( ui_ScreenGauge_Label_speed, -4 );
lv_obj_set_align( ui_ScreenGauge_Label_speed, LV_ALIGN_CENTER );
lv_label_set_text(ui_ScreenGauge_Label_speed,"0");
lv_obj_set_style_text_align(ui_ScreenGauge_Label_speed, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ScreenGauge_Label_gear = lv_label_create(ui_ScreenGauge_Container_roundgauge);
lv_obj_set_width( ui_ScreenGauge_Label_gear, 38);
lv_obj_set_height( ui_ScreenGauge_Label_gear, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ScreenGauge_Label_gear, 0 );
lv_obj_set_y( ui_ScreenGauge_Label_gear, 49 );
lv_obj_set_align( ui_ScreenGauge_Label_gear, LV_ALIGN_CENTER );
lv_label_set_text(ui_ScreenGauge_Label_gear,"-");
lv_obj_set_style_text_color(ui_ScreenGauge_Label_gear, lv_color_hex(0xFFA000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ScreenGauge_Label_gear, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_ScreenGauge_Label_gear, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_ScreenGauge_Label_gear, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_ScreenGauge_Label_gear, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ScreenGauge_Label_gear, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_ScreenGauge_Label_gear, lv_color_hex(0x555555), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_ScreenGauge_Label_gear, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_width(ui_ScreenGauge_Label_gear, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_pad(ui_ScreenGauge_Label_gear, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_ScreenGauge_Label_gear, lv_color_hex(0x222222), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_ScreenGauge_Label_gear, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_ScreenGauge_Label_gear, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_ScreenGauge_Label_gear, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ScreenGauge_Label_RPMx1000 = lv_label_create(ui_ScreenGauge_Container_roundgauge);
lv_obj_set_width( ui_ScreenGauge_Label_RPMx1000, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ScreenGauge_Label_RPMx1000, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ScreenGauge_Label_RPMx1000, -36 );
lv_obj_set_y( ui_ScreenGauge_Label_RPMx1000, 44 );
lv_obj_set_align( ui_ScreenGauge_Label_RPMx1000, LV_ALIGN_CENTER );
lv_label_set_text(ui_ScreenGauge_Label_RPMx1000,"RPM\nx1000");
lv_obj_set_style_text_font(ui_ScreenGauge_Label_RPMx1000, &lv_font_montserrat_8, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ScreenGauge_Label_kmh = lv_label_create(ui_ScreenGauge_Container_roundgauge);
lv_obj_set_width( ui_ScreenGauge_Label_kmh, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ScreenGauge_Label_kmh, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ScreenGauge_Label_kmh, 0 );
lv_obj_set_y( ui_ScreenGauge_Label_kmh, 18 );
lv_obj_set_align( ui_ScreenGauge_Label_kmh, LV_ALIGN_CENTER );
lv_label_set_text(ui_ScreenGauge_Label_kmh,"km/h");
lv_obj_set_style_text_font(ui_ScreenGauge_Label_kmh, &lv_font_montserrat_8, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_Screen_ScreenGauge, ui_event_Screen_ScreenGauge, LV_EVENT_ALL, NULL);

}

void ui_Screen_ScreenGauge_screen_destroy(void)
{
   if (ui_Screen_ScreenGauge) lv_obj_del(ui_Screen_ScreenGauge);

// NULL screen variables
ui_Screen_ScreenGauge= NULL;
ui_ScreenGauge_Container_Container1= NULL;
ui_ScreenGauge_Label_number1= NULL;
ui_ScreenGauge_Label_pid1= NULL;
ui_ScreenGauge_Label_unit1= NULL;
ui_ScreenGauge_Container_Container2= NULL;
ui_ScreenGauge_Label_number2= NULL;
ui_ScreenGauge_Label_pid2= NULL;
ui_ScreenGauge_Label_unit2= NULL;
ui_ScreenGauge_Container_Container3= NULL;
ui_ScreenGauge_Label_number3= NULL;
ui_ScreenGauge_Label_pid3= NULL;
ui_ScreenGauge_Label_unit3= NULL;
ui_ScreenGauge_Container_Container4= NULL;
ui_ScreenGauge_Label_number4= NULL;
ui_ScreenGauge_Label_pid4= NULL;
ui_ScreenGauge_Label_unit4= NULL;
ui_ScreenGauge_Container_Container5= NULL;
ui_ScreenGauge_Label_number5= NULL;
ui_ScreenGauge_Label_pid5= NULL;
ui_ScreenGauge_Label_unit5= NULL;
ui_ScreenGauge_Container_Container6= NULL;
ui_ScreenGauge_Label_number6= NULL;
ui_ScreenGauge_Label_pid6= NULL;
ui_ScreenGauge_Label_unit6= NULL;
ui_ScreenGauge_Container_container7= NULL;
ui_ScreenGauge_Label_number7= NULL;
ui_ScreenGauge_Label_pid7= NULL;
ui_ScreenGauge_Label_unit7= NULL;
ui_ScreenGauge_Container_container8= NULL;
ui_ScreenGauge_Label_info1= NULL;
ui_ScreenGauge_Container_roundgauge= NULL;
ui_ScreenGauge_Arc_rpm= NULL;
ui_ScreenGauge_Label_speed= NULL;
ui_ScreenGauge_Label_gear= NULL;
ui_ScreenGauge_Label_RPMx1000= NULL;
ui_ScreenGauge_Label_kmh= NULL;

}
