// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: obd2_gauge_catalyst

#ifndef UI_SCREEN_SCREENGAUGE_H
#define UI_SCREEN_SCREENGAUGE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen_ScreenGauge
extern void ui_Screen_ScreenGauge_screen_init(void);
extern void ui_Screen_ScreenGauge_screen_destroy(void);
extern void ui_event_Screen_ScreenGauge( lv_event_t * e);
extern lv_obj_t *ui_Screen_ScreenGauge;
extern lv_obj_t *ui_ScreenGauge_Container_Container1;
extern lv_obj_t *ui_ScreenGauge_Label_number1;
extern lv_obj_t *ui_ScreenGauge_Label_pid1;
extern lv_obj_t *ui_ScreenGauge_Label_unit1;
extern lv_obj_t *ui_ScreenGauge_Container_Container2;
extern lv_obj_t *ui_ScreenGauge_Label_number2;
extern lv_obj_t *ui_ScreenGauge_Label_pid2;
extern lv_obj_t *ui_ScreenGauge_Label_unit2;
extern lv_obj_t *ui_ScreenGauge_Container_Container3;
extern lv_obj_t *ui_ScreenGauge_Label_number3;
extern lv_obj_t *ui_ScreenGauge_Label_pid3;
extern lv_obj_t *ui_ScreenGauge_Label_unit3;
extern lv_obj_t *ui_ScreenGauge_Container_Container4;
extern lv_obj_t *ui_ScreenGauge_Label_number4;
extern lv_obj_t *ui_ScreenGauge_Label_pid4;
extern lv_obj_t *ui_ScreenGauge_Label_unit4;
extern lv_obj_t *ui_ScreenGauge_Container_Container5;
extern lv_obj_t *ui_ScreenGauge_Label_number5;
extern lv_obj_t *ui_ScreenGauge_Label_pid5;
extern lv_obj_t *ui_ScreenGauge_Label_unit5;
extern lv_obj_t *ui_ScreenGauge_Container_Container6;
extern lv_obj_t *ui_ScreenGauge_Label_number6;
extern lv_obj_t *ui_ScreenGauge_Label_pid6;
extern lv_obj_t *ui_ScreenGauge_Label_unit6;
extern lv_obj_t *ui_ScreenGauge_Container_container7;
extern lv_obj_t *ui_ScreenGauge_Label_number7;
extern lv_obj_t *ui_ScreenGauge_Label_pid7;
extern lv_obj_t *ui_ScreenGauge_Label_unit7;
extern lv_obj_t *ui_ScreenGauge_Container_container8;
extern lv_obj_t *ui_ScreenGauge_Label_info1;
extern lv_obj_t *ui_ScreenGauge_Container_roundgauge;
extern lv_obj_t *ui_ScreenGauge_Arc_rpm;
extern lv_obj_t *ui_ScreenGauge_Label_speed;
extern lv_obj_t *ui_ScreenGauge_Label_gear;
extern lv_obj_t *ui_ScreenGauge_Label_RPMx1000;
extern lv_obj_t *ui_ScreenGauge_Label_kmh;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

