// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: obd2_gauge_catalyst

#ifndef UI_SCREEN_SCREENSERVICE_H
#define UI_SCREEN_SCREENSERVICE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen_ScreenService
extern void ui_Screen_ScreenService_screen_init(void);
extern void ui_Screen_ScreenService_screen_destroy(void);
extern void ui_event_Screen_ScreenService( lv_event_t * e);
extern lv_obj_t *ui_Screen_ScreenService;
extern void ui_event_ScreenService_Tabview_Service( lv_event_t * e);
extern lv_obj_t *ui_ScreenService_Tabview_Service;
extern lv_obj_t *ui_ScreenService_Tabpage_Warning;
extern void ui_event_ScreenService_Roller_warnList( lv_event_t * e);
extern lv_obj_t *ui_ScreenService_Roller_warnList;
extern void ui_event_ScreenService_Slider_limit( lv_event_t * e);
extern lv_obj_t *ui_ScreenService_Slider_limit;
extern lv_obj_t *ui_ScreenService_Label_min;
extern lv_obj_t *ui_ScreenService_Label_max;
extern lv_obj_t *ui_ScreenService_Button_saveWarn;
extern lv_obj_t *ui_ScreenService_Label_Save1;
extern lv_obj_t *ui_ScreenService_Button_setDefault;
extern lv_obj_t *ui_ScreenService_Label_Save2;
extern lv_obj_t *ui_ScreenService_Label_warnValue;
extern lv_obj_t *ui_ScreenService_Tabpage_Diagnostics;
extern void ui_event_ScreenService_Button_readDTC( lv_event_t * e);
extern lv_obj_t *ui_ScreenService_Button_readDTC;
extern lv_obj_t *ui_ScreenService_Label_Label5;
extern void ui_event_ScreenService_Button_updateDescription( lv_event_t * e);
extern lv_obj_t *ui_ScreenService_Button_updateDescription;
extern lv_obj_t *ui_ScreenService_Label_Label10;
extern lv_obj_t *ui_ScreenService_Label_pleasewait;
extern lv_obj_t *ui_ScreenService_Panel_dtc;
extern void ui_event_ScreenService_Button_clearMIL( lv_event_t * e);
extern lv_obj_t *ui_ScreenService_Button_clearMIL;
extern lv_obj_t *ui_ScreenService_Label_Label7;
extern lv_obj_t *ui_ScreenService_Textarea_DTCList;
extern lv_obj_t *ui_ScreenService_Label_MILStatus;
extern void ui_event_ScreenService_Button_closeDTC( lv_event_t * e);
extern lv_obj_t *ui_ScreenService_Button_closeDTC;
extern lv_obj_t *ui_ScreenService_Label_Label8;
extern lv_obj_t *ui_ScreenService_Image_Image1;
extern lv_obj_t *ui_ScreenService_Image_Image2;
extern void ui_event_ScreenService_Button_swipeUp( lv_event_t * e);
extern lv_obj_t *ui_ScreenService_Button_swipeUp;
extern lv_obj_t *ui_ScreenService_Label_upup;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

