// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: obd2_gauge_catalyst

#include "ui.h"

lv_obj_t *ui_Screen_ScreenMonitor = NULL;lv_obj_t *ui_ScreenMonitor_Container_tile1 = NULL;lv_obj_t *ui_ScreenMonitor_Label_tileNumber1 = NULL;lv_obj_t *ui_ScreenMonitor_Label_tilePid1 = NULL;lv_obj_t *ui_ScreenMonitor_Label_tileUnit1 = NULL;lv_obj_t *ui_ScreenMonitor_Container_tile2 = NULL;lv_obj_t *ui_ScreenMonitor_Label_tileNumber2 = NULL;lv_obj_t *ui_ScreenMonitor_Label_tilePid2 = NULL;lv_obj_t *ui_ScreenMonitor_Label_tileUnit2 = NULL;lv_obj_t *ui_ScreenMonitor_Container_tile3 = NULL;lv_obj_t *ui_ScreenMonitor_Label_tileNumber3 = NULL;lv_obj_t *ui_ScreenMonitor_Label_tilePid3 = NULL;lv_obj_t *ui_ScreenMonitor_Label_tileUnit3 = NULL;lv_obj_t *ui_ScreenMonitor_Container_tile4 = NULL;lv_obj_t *ui_ScreenMonitor_Label_tileNumber4 = NULL;lv_obj_t *ui_ScreenMonitor_Label_tilePid4 = NULL;lv_obj_t *ui_ScreenMonitor_Label_tileUnit4 = NULL;lv_obj_t *ui_ScreenMonitor_Container_tile5 = NULL;lv_obj_t *ui_ScreenMonitor_Label_tileNumber5 = NULL;lv_obj_t *ui_ScreenMonitor_Label_tilePid5 = NULL;lv_obj_t *ui_ScreenMonitor_Label_tileUnit5 = NULL;lv_obj_t *ui_ScreenMonitor_Container_tile6 = NULL;lv_obj_t *ui_ScreenMonitor_Label_tileNumber6 = NULL;lv_obj_t *ui_ScreenMonitor_Label_tilePid6 = NULL;lv_obj_t *ui_ScreenMonitor_Label_tileUnit6 = NULL;lv_obj_t *ui_ScreenMonitor_Container_tile7 = NULL;lv_obj_t *ui_ScreenMonitor_Label_tileNumber7 = NULL;lv_obj_t *ui_ScreenMonitor_Label_tilePid7 = NULL;lv_obj_t *ui_ScreenMonitor_Label_tileUnit7 = NULL;lv_obj_t *ui_ScreenMonitor_Container_tile8 = NULL;lv_obj_t *ui_ScreenMonitor_Label_tileNumber8 = NULL;lv_obj_t *ui_ScreenMonitor_Label_tilePid8 = NULL;lv_obj_t *ui_ScreenMonitor_Label_tileUnit8 = NULL;lv_obj_t *ui_ScreenMonitor_Container_tile9 = NULL;lv_obj_t *ui_ScreenMonitor_Label_tileNumber9 = NULL;lv_obj_t *ui_ScreenMonitor_Label_tilePid9 = NULL;lv_obj_t *ui_ScreenMonitor_Label_tileUnit9 = NULL;lv_obj_t *ui_ScreenMonitor_Button_swipeLeft = NULL;lv_obj_t *ui_ScreenMonitor_Label_left = NULL;lv_obj_t *ui_ScreenMonitor_Label_info2 = NULL;
// event funtions
void ui_event_Screen_ScreenMonitor( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT  ) {
lv_indev_wait_release(lv_indev_get_act());
      _ui_screen_change( &ui_Screen_ScreenGauge, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_Screen_ScreenGauge_screen_init);
      changeScreenGauge( e );
}
}

void ui_event_ScreenMonitor_Button_swipeLeft( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Screen_ScreenGauge, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_Screen_ScreenGauge_screen_init);
      changeScreenGauge( e );
}
}

// build funtions

void ui_Screen_ScreenMonitor_screen_init(void)
{
ui_Screen_ScreenMonitor = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen_ScreenMonitor, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Screen_ScreenMonitor, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Screen_ScreenMonitor, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_Screen_ScreenMonitor, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Screen_ScreenMonitor, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Screen_ScreenMonitor, &ui_font_oswald_36, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ScreenMonitor_Container_tile1 = lv_obj_create(ui_Screen_ScreenMonitor);
lv_obj_remove_style_all(ui_ScreenMonitor_Container_tile1);
lv_obj_set_width( ui_ScreenMonitor_Container_tile1, 106);
lv_obj_set_height( ui_ScreenMonitor_Container_tile1, 80);
lv_obj_clear_flag( ui_ScreenMonitor_Container_tile1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_radius(ui_ScreenMonitor_Container_tile1, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_ScreenMonitor_Container_tile1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ScreenMonitor_Container_tile1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_ScreenMonitor_Container_tile1, lv_color_hex(0x00007F), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_main_stop(ui_ScreenMonitor_Container_tile1, 120, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_stop(ui_ScreenMonitor_Container_tile1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_dir(ui_ScreenMonitor_Container_tile1, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_ScreenMonitor_Container_tile1, lv_color_hex(0x0000FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_ScreenMonitor_Container_tile1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_ScreenMonitor_Container_tile1, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ScreenMonitor_Label_tileNumber1 = lv_label_create(ui_ScreenMonitor_Container_tile1);
lv_obj_set_width( ui_ScreenMonitor_Label_tileNumber1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ScreenMonitor_Label_tileNumber1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ScreenMonitor_Label_tileNumber1, 0 );
lv_obj_set_y( ui_ScreenMonitor_Label_tileNumber1, 8 );
lv_obj_set_align( ui_ScreenMonitor_Label_tileNumber1, LV_ALIGN_CENTER );
lv_label_set_text(ui_ScreenMonitor_Label_tileNumber1,"0");

ui_ScreenMonitor_Label_tilePid1 = lv_label_create(ui_ScreenMonitor_Container_tile1);
lv_obj_set_width( ui_ScreenMonitor_Label_tilePid1, lv_pct(100));
lv_obj_set_height( ui_ScreenMonitor_Label_tilePid1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_ScreenMonitor_Label_tilePid1, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_ScreenMonitor_Label_tilePid1,"-");
lv_obj_set_style_text_color(ui_ScreenMonitor_Label_tilePid1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ScreenMonitor_Label_tilePid1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_ScreenMonitor_Label_tilePid1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_ScreenMonitor_Label_tilePid1, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_ScreenMonitor_Label_tilePid1, lv_color_hex(0xCCCCCC), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ScreenMonitor_Label_tilePid1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ScreenMonitor_Label_tileUnit1 = lv_label_create(ui_ScreenMonitor_Container_tile1);
lv_obj_set_width( ui_ScreenMonitor_Label_tileUnit1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ScreenMonitor_Label_tileUnit1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_ScreenMonitor_Label_tileUnit1, LV_ALIGN_BOTTOM_MID );
lv_label_set_text(ui_ScreenMonitor_Label_tileUnit1,"-");
lv_obj_set_style_text_color(ui_ScreenMonitor_Label_tileUnit1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ScreenMonitor_Label_tileUnit1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_ScreenMonitor_Label_tileUnit1, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ScreenMonitor_Container_tile2 = lv_obj_create(ui_Screen_ScreenMonitor);
lv_obj_remove_style_all(ui_ScreenMonitor_Container_tile2);
lv_obj_set_width( ui_ScreenMonitor_Container_tile2, 106);
lv_obj_set_height( ui_ScreenMonitor_Container_tile2, 80);
lv_obj_set_align( ui_ScreenMonitor_Container_tile2, LV_ALIGN_TOP_MID );
lv_obj_clear_flag( ui_ScreenMonitor_Container_tile2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_radius(ui_ScreenMonitor_Container_tile2, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_ScreenMonitor_Container_tile2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ScreenMonitor_Container_tile2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_ScreenMonitor_Container_tile2, lv_color_hex(0x00007F), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_main_stop(ui_ScreenMonitor_Container_tile2, 120, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_stop(ui_ScreenMonitor_Container_tile2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_dir(ui_ScreenMonitor_Container_tile2, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_ScreenMonitor_Container_tile2, lv_color_hex(0x0000FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_ScreenMonitor_Container_tile2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_ScreenMonitor_Container_tile2, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ScreenMonitor_Label_tileNumber2 = lv_label_create(ui_ScreenMonitor_Container_tile2);
lv_obj_set_width( ui_ScreenMonitor_Label_tileNumber2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ScreenMonitor_Label_tileNumber2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ScreenMonitor_Label_tileNumber2, 0 );
lv_obj_set_y( ui_ScreenMonitor_Label_tileNumber2, 8 );
lv_obj_set_align( ui_ScreenMonitor_Label_tileNumber2, LV_ALIGN_CENTER );
lv_label_set_text(ui_ScreenMonitor_Label_tileNumber2,"0");

ui_ScreenMonitor_Label_tilePid2 = lv_label_create(ui_ScreenMonitor_Container_tile2);
lv_obj_set_width( ui_ScreenMonitor_Label_tilePid2, lv_pct(100));
lv_obj_set_height( ui_ScreenMonitor_Label_tilePid2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_ScreenMonitor_Label_tilePid2, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_ScreenMonitor_Label_tilePid2,"-");
lv_obj_set_style_text_color(ui_ScreenMonitor_Label_tilePid2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ScreenMonitor_Label_tilePid2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_ScreenMonitor_Label_tilePid2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_ScreenMonitor_Label_tilePid2, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_ScreenMonitor_Label_tilePid2, lv_color_hex(0xCCCCCC), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ScreenMonitor_Label_tilePid2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ScreenMonitor_Label_tileUnit2 = lv_label_create(ui_ScreenMonitor_Container_tile2);
lv_obj_set_width( ui_ScreenMonitor_Label_tileUnit2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ScreenMonitor_Label_tileUnit2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_ScreenMonitor_Label_tileUnit2, LV_ALIGN_BOTTOM_MID );
lv_label_set_text(ui_ScreenMonitor_Label_tileUnit2,"-");
lv_obj_set_style_text_color(ui_ScreenMonitor_Label_tileUnit2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ScreenMonitor_Label_tileUnit2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_ScreenMonitor_Label_tileUnit2, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ScreenMonitor_Container_tile3 = lv_obj_create(ui_Screen_ScreenMonitor);
lv_obj_remove_style_all(ui_ScreenMonitor_Container_tile3);
lv_obj_set_width( ui_ScreenMonitor_Container_tile3, 106);
lv_obj_set_height( ui_ScreenMonitor_Container_tile3, 80);
lv_obj_set_align( ui_ScreenMonitor_Container_tile3, LV_ALIGN_TOP_RIGHT );
lv_obj_clear_flag( ui_ScreenMonitor_Container_tile3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_radius(ui_ScreenMonitor_Container_tile3, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_ScreenMonitor_Container_tile3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ScreenMonitor_Container_tile3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_ScreenMonitor_Container_tile3, lv_color_hex(0x00007F), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_main_stop(ui_ScreenMonitor_Container_tile3, 120, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_stop(ui_ScreenMonitor_Container_tile3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_dir(ui_ScreenMonitor_Container_tile3, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_ScreenMonitor_Container_tile3, lv_color_hex(0x0000FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_ScreenMonitor_Container_tile3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_ScreenMonitor_Container_tile3, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ScreenMonitor_Label_tileNumber3 = lv_label_create(ui_ScreenMonitor_Container_tile3);
lv_obj_set_width( ui_ScreenMonitor_Label_tileNumber3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ScreenMonitor_Label_tileNumber3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ScreenMonitor_Label_tileNumber3, 0 );
lv_obj_set_y( ui_ScreenMonitor_Label_tileNumber3, 8 );
lv_obj_set_align( ui_ScreenMonitor_Label_tileNumber3, LV_ALIGN_CENTER );
lv_label_set_text(ui_ScreenMonitor_Label_tileNumber3,"0");

ui_ScreenMonitor_Label_tilePid3 = lv_label_create(ui_ScreenMonitor_Container_tile3);
lv_obj_set_width( ui_ScreenMonitor_Label_tilePid3, lv_pct(100));
lv_obj_set_height( ui_ScreenMonitor_Label_tilePid3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_ScreenMonitor_Label_tilePid3, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_ScreenMonitor_Label_tilePid3,"-");
lv_obj_set_style_text_color(ui_ScreenMonitor_Label_tilePid3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ScreenMonitor_Label_tilePid3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_ScreenMonitor_Label_tilePid3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_ScreenMonitor_Label_tilePid3, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_ScreenMonitor_Label_tilePid3, lv_color_hex(0xCCCCCC), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ScreenMonitor_Label_tilePid3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ScreenMonitor_Label_tileUnit3 = lv_label_create(ui_ScreenMonitor_Container_tile3);
lv_obj_set_width( ui_ScreenMonitor_Label_tileUnit3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ScreenMonitor_Label_tileUnit3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_ScreenMonitor_Label_tileUnit3, LV_ALIGN_BOTTOM_MID );
lv_label_set_text(ui_ScreenMonitor_Label_tileUnit3,"-");
lv_obj_set_style_text_color(ui_ScreenMonitor_Label_tileUnit3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ScreenMonitor_Label_tileUnit3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_ScreenMonitor_Label_tileUnit3, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ScreenMonitor_Container_tile4 = lv_obj_create(ui_Screen_ScreenMonitor);
lv_obj_remove_style_all(ui_ScreenMonitor_Container_tile4);
lv_obj_set_width( ui_ScreenMonitor_Container_tile4, 106);
lv_obj_set_height( ui_ScreenMonitor_Container_tile4, 80);
lv_obj_set_align( ui_ScreenMonitor_Container_tile4, LV_ALIGN_LEFT_MID );
lv_obj_clear_flag( ui_ScreenMonitor_Container_tile4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_radius(ui_ScreenMonitor_Container_tile4, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_ScreenMonitor_Container_tile4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ScreenMonitor_Container_tile4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_ScreenMonitor_Container_tile4, lv_color_hex(0x00007F), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_main_stop(ui_ScreenMonitor_Container_tile4, 120, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_stop(ui_ScreenMonitor_Container_tile4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_dir(ui_ScreenMonitor_Container_tile4, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_ScreenMonitor_Container_tile4, lv_color_hex(0x0000FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_ScreenMonitor_Container_tile4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_ScreenMonitor_Container_tile4, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ScreenMonitor_Label_tileNumber4 = lv_label_create(ui_ScreenMonitor_Container_tile4);
lv_obj_set_width( ui_ScreenMonitor_Label_tileNumber4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ScreenMonitor_Label_tileNumber4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ScreenMonitor_Label_tileNumber4, 0 );
lv_obj_set_y( ui_ScreenMonitor_Label_tileNumber4, 8 );
lv_obj_set_align( ui_ScreenMonitor_Label_tileNumber4, LV_ALIGN_CENTER );
lv_label_set_text(ui_ScreenMonitor_Label_tileNumber4,"0");

ui_ScreenMonitor_Label_tilePid4 = lv_label_create(ui_ScreenMonitor_Container_tile4);
lv_obj_set_width( ui_ScreenMonitor_Label_tilePid4, lv_pct(100));
lv_obj_set_height( ui_ScreenMonitor_Label_tilePid4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_ScreenMonitor_Label_tilePid4, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_ScreenMonitor_Label_tilePid4,"-");
lv_obj_set_style_text_color(ui_ScreenMonitor_Label_tilePid4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ScreenMonitor_Label_tilePid4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_ScreenMonitor_Label_tilePid4, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_ScreenMonitor_Label_tilePid4, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_ScreenMonitor_Label_tilePid4, lv_color_hex(0xFFB700), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ScreenMonitor_Label_tilePid4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ScreenMonitor_Label_tileUnit4 = lv_label_create(ui_ScreenMonitor_Container_tile4);
lv_obj_set_width( ui_ScreenMonitor_Label_tileUnit4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ScreenMonitor_Label_tileUnit4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_ScreenMonitor_Label_tileUnit4, LV_ALIGN_BOTTOM_MID );
lv_label_set_text(ui_ScreenMonitor_Label_tileUnit4,"-");
lv_obj_set_style_text_color(ui_ScreenMonitor_Label_tileUnit4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ScreenMonitor_Label_tileUnit4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_ScreenMonitor_Label_tileUnit4, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ScreenMonitor_Container_tile5 = lv_obj_create(ui_Screen_ScreenMonitor);
lv_obj_remove_style_all(ui_ScreenMonitor_Container_tile5);
lv_obj_set_width( ui_ScreenMonitor_Container_tile5, 106);
lv_obj_set_height( ui_ScreenMonitor_Container_tile5, 80);
lv_obj_set_align( ui_ScreenMonitor_Container_tile5, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_ScreenMonitor_Container_tile5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_radius(ui_ScreenMonitor_Container_tile5, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_ScreenMonitor_Container_tile5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ScreenMonitor_Container_tile5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_ScreenMonitor_Container_tile5, lv_color_hex(0x00007F), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_main_stop(ui_ScreenMonitor_Container_tile5, 120, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_stop(ui_ScreenMonitor_Container_tile5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_dir(ui_ScreenMonitor_Container_tile5, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_ScreenMonitor_Container_tile5, lv_color_hex(0x0000FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_ScreenMonitor_Container_tile5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_ScreenMonitor_Container_tile5, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ScreenMonitor_Label_tileNumber5 = lv_label_create(ui_ScreenMonitor_Container_tile5);
lv_obj_set_width( ui_ScreenMonitor_Label_tileNumber5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ScreenMonitor_Label_tileNumber5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ScreenMonitor_Label_tileNumber5, 0 );
lv_obj_set_y( ui_ScreenMonitor_Label_tileNumber5, 8 );
lv_obj_set_align( ui_ScreenMonitor_Label_tileNumber5, LV_ALIGN_CENTER );
lv_label_set_text(ui_ScreenMonitor_Label_tileNumber5,"0");

ui_ScreenMonitor_Label_tilePid5 = lv_label_create(ui_ScreenMonitor_Container_tile5);
lv_obj_set_width( ui_ScreenMonitor_Label_tilePid5, lv_pct(100));
lv_obj_set_height( ui_ScreenMonitor_Label_tilePid5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_ScreenMonitor_Label_tilePid5, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_ScreenMonitor_Label_tilePid5,"-");
lv_obj_set_style_text_color(ui_ScreenMonitor_Label_tilePid5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ScreenMonitor_Label_tilePid5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_ScreenMonitor_Label_tilePid5, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_ScreenMonitor_Label_tilePid5, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_ScreenMonitor_Label_tilePid5, lv_color_hex(0xFFB700), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ScreenMonitor_Label_tilePid5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ScreenMonitor_Label_tileUnit5 = lv_label_create(ui_ScreenMonitor_Container_tile5);
lv_obj_set_width( ui_ScreenMonitor_Label_tileUnit5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ScreenMonitor_Label_tileUnit5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_ScreenMonitor_Label_tileUnit5, LV_ALIGN_BOTTOM_MID );
lv_label_set_text(ui_ScreenMonitor_Label_tileUnit5,"-");
lv_obj_set_style_text_color(ui_ScreenMonitor_Label_tileUnit5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ScreenMonitor_Label_tileUnit5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_ScreenMonitor_Label_tileUnit5, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ScreenMonitor_Container_tile6 = lv_obj_create(ui_Screen_ScreenMonitor);
lv_obj_remove_style_all(ui_ScreenMonitor_Container_tile6);
lv_obj_set_width( ui_ScreenMonitor_Container_tile6, 106);
lv_obj_set_height( ui_ScreenMonitor_Container_tile6, 80);
lv_obj_set_align( ui_ScreenMonitor_Container_tile6, LV_ALIGN_RIGHT_MID );
lv_obj_clear_flag( ui_ScreenMonitor_Container_tile6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_radius(ui_ScreenMonitor_Container_tile6, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_ScreenMonitor_Container_tile6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ScreenMonitor_Container_tile6, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_ScreenMonitor_Container_tile6, lv_color_hex(0x00007F), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_main_stop(ui_ScreenMonitor_Container_tile6, 120, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_stop(ui_ScreenMonitor_Container_tile6, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_dir(ui_ScreenMonitor_Container_tile6, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_ScreenMonitor_Container_tile6, lv_color_hex(0x0000FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_ScreenMonitor_Container_tile6, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_ScreenMonitor_Container_tile6, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ScreenMonitor_Label_tileNumber6 = lv_label_create(ui_ScreenMonitor_Container_tile6);
lv_obj_set_width( ui_ScreenMonitor_Label_tileNumber6, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ScreenMonitor_Label_tileNumber6, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ScreenMonitor_Label_tileNumber6, 0 );
lv_obj_set_y( ui_ScreenMonitor_Label_tileNumber6, 8 );
lv_obj_set_align( ui_ScreenMonitor_Label_tileNumber6, LV_ALIGN_CENTER );
lv_label_set_text(ui_ScreenMonitor_Label_tileNumber6,"0");

ui_ScreenMonitor_Label_tilePid6 = lv_label_create(ui_ScreenMonitor_Container_tile6);
lv_obj_set_width( ui_ScreenMonitor_Label_tilePid6, lv_pct(100));
lv_obj_set_height( ui_ScreenMonitor_Label_tilePid6, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_ScreenMonitor_Label_tilePid6, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_ScreenMonitor_Label_tilePid6,"-");
lv_obj_set_style_text_color(ui_ScreenMonitor_Label_tilePid6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ScreenMonitor_Label_tilePid6, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_ScreenMonitor_Label_tilePid6, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_ScreenMonitor_Label_tilePid6, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_ScreenMonitor_Label_tilePid6, lv_color_hex(0xFFB700), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ScreenMonitor_Label_tilePid6, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ScreenMonitor_Label_tileUnit6 = lv_label_create(ui_ScreenMonitor_Container_tile6);
lv_obj_set_width( ui_ScreenMonitor_Label_tileUnit6, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ScreenMonitor_Label_tileUnit6, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_ScreenMonitor_Label_tileUnit6, LV_ALIGN_BOTTOM_MID );
lv_label_set_text(ui_ScreenMonitor_Label_tileUnit6,"-");
lv_obj_set_style_text_color(ui_ScreenMonitor_Label_tileUnit6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ScreenMonitor_Label_tileUnit6, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_ScreenMonitor_Label_tileUnit6, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ScreenMonitor_Container_tile7 = lv_obj_create(ui_Screen_ScreenMonitor);
lv_obj_remove_style_all(ui_ScreenMonitor_Container_tile7);
lv_obj_set_width( ui_ScreenMonitor_Container_tile7, 106);
lv_obj_set_height( ui_ScreenMonitor_Container_tile7, 80);
lv_obj_set_align( ui_ScreenMonitor_Container_tile7, LV_ALIGN_BOTTOM_LEFT );
lv_obj_clear_flag( ui_ScreenMonitor_Container_tile7, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_radius(ui_ScreenMonitor_Container_tile7, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_ScreenMonitor_Container_tile7, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ScreenMonitor_Container_tile7, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_ScreenMonitor_Container_tile7, lv_color_hex(0x00007F), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_main_stop(ui_ScreenMonitor_Container_tile7, 120, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_stop(ui_ScreenMonitor_Container_tile7, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_dir(ui_ScreenMonitor_Container_tile7, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_ScreenMonitor_Container_tile7, lv_color_hex(0x0000FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_ScreenMonitor_Container_tile7, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_ScreenMonitor_Container_tile7, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ScreenMonitor_Label_tileNumber7 = lv_label_create(ui_ScreenMonitor_Container_tile7);
lv_obj_set_width( ui_ScreenMonitor_Label_tileNumber7, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ScreenMonitor_Label_tileNumber7, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ScreenMonitor_Label_tileNumber7, 0 );
lv_obj_set_y( ui_ScreenMonitor_Label_tileNumber7, 8 );
lv_obj_set_align( ui_ScreenMonitor_Label_tileNumber7, LV_ALIGN_CENTER );
lv_label_set_text(ui_ScreenMonitor_Label_tileNumber7,"0");

ui_ScreenMonitor_Label_tilePid7 = lv_label_create(ui_ScreenMonitor_Container_tile7);
lv_obj_set_width( ui_ScreenMonitor_Label_tilePid7, lv_pct(100));
lv_obj_set_height( ui_ScreenMonitor_Label_tilePid7, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_ScreenMonitor_Label_tilePid7, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_ScreenMonitor_Label_tilePid7,"-");
lv_obj_set_style_text_color(ui_ScreenMonitor_Label_tilePid7, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ScreenMonitor_Label_tilePid7, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_ScreenMonitor_Label_tilePid7, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_ScreenMonitor_Label_tilePid7, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_ScreenMonitor_Label_tilePid7, lv_color_hex(0xFE65FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ScreenMonitor_Label_tilePid7, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ScreenMonitor_Label_tileUnit7 = lv_label_create(ui_ScreenMonitor_Container_tile7);
lv_obj_set_width( ui_ScreenMonitor_Label_tileUnit7, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ScreenMonitor_Label_tileUnit7, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_ScreenMonitor_Label_tileUnit7, LV_ALIGN_BOTTOM_MID );
lv_label_set_text(ui_ScreenMonitor_Label_tileUnit7,"-");
lv_obj_set_style_text_color(ui_ScreenMonitor_Label_tileUnit7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ScreenMonitor_Label_tileUnit7, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_ScreenMonitor_Label_tileUnit7, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ScreenMonitor_Container_tile8 = lv_obj_create(ui_Screen_ScreenMonitor);
lv_obj_remove_style_all(ui_ScreenMonitor_Container_tile8);
lv_obj_set_width( ui_ScreenMonitor_Container_tile8, 106);
lv_obj_set_height( ui_ScreenMonitor_Container_tile8, 80);
lv_obj_set_align( ui_ScreenMonitor_Container_tile8, LV_ALIGN_BOTTOM_MID );
lv_obj_clear_flag( ui_ScreenMonitor_Container_tile8, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_radius(ui_ScreenMonitor_Container_tile8, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_ScreenMonitor_Container_tile8, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ScreenMonitor_Container_tile8, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_ScreenMonitor_Container_tile8, lv_color_hex(0x00007F), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_main_stop(ui_ScreenMonitor_Container_tile8, 120, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_stop(ui_ScreenMonitor_Container_tile8, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_dir(ui_ScreenMonitor_Container_tile8, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_ScreenMonitor_Container_tile8, lv_color_hex(0x0000FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_ScreenMonitor_Container_tile8, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_ScreenMonitor_Container_tile8, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ScreenMonitor_Label_tileNumber8 = lv_label_create(ui_ScreenMonitor_Container_tile8);
lv_obj_set_width( ui_ScreenMonitor_Label_tileNumber8, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ScreenMonitor_Label_tileNumber8, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ScreenMonitor_Label_tileNumber8, 0 );
lv_obj_set_y( ui_ScreenMonitor_Label_tileNumber8, 8 );
lv_obj_set_align( ui_ScreenMonitor_Label_tileNumber8, LV_ALIGN_CENTER );
lv_label_set_text(ui_ScreenMonitor_Label_tileNumber8,"0");

ui_ScreenMonitor_Label_tilePid8 = lv_label_create(ui_ScreenMonitor_Container_tile8);
lv_obj_set_width( ui_ScreenMonitor_Label_tilePid8, lv_pct(100));
lv_obj_set_height( ui_ScreenMonitor_Label_tilePid8, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_ScreenMonitor_Label_tilePid8, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_ScreenMonitor_Label_tilePid8,"-");
lv_obj_set_style_text_color(ui_ScreenMonitor_Label_tilePid8, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ScreenMonitor_Label_tilePid8, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_ScreenMonitor_Label_tilePid8, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_ScreenMonitor_Label_tilePid8, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_ScreenMonitor_Label_tilePid8, lv_color_hex(0xFE65FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ScreenMonitor_Label_tilePid8, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ScreenMonitor_Label_tileUnit8 = lv_label_create(ui_ScreenMonitor_Container_tile8);
lv_obj_set_width( ui_ScreenMonitor_Label_tileUnit8, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ScreenMonitor_Label_tileUnit8, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_ScreenMonitor_Label_tileUnit8, LV_ALIGN_BOTTOM_MID );
lv_label_set_text(ui_ScreenMonitor_Label_tileUnit8,"-");
lv_obj_set_style_text_color(ui_ScreenMonitor_Label_tileUnit8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ScreenMonitor_Label_tileUnit8, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_ScreenMonitor_Label_tileUnit8, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ScreenMonitor_Container_tile9 = lv_obj_create(ui_Screen_ScreenMonitor);
lv_obj_remove_style_all(ui_ScreenMonitor_Container_tile9);
lv_obj_set_width( ui_ScreenMonitor_Container_tile9, 106);
lv_obj_set_height( ui_ScreenMonitor_Container_tile9, 80);
lv_obj_set_align( ui_ScreenMonitor_Container_tile9, LV_ALIGN_BOTTOM_RIGHT );
lv_obj_clear_flag( ui_ScreenMonitor_Container_tile9, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_radius(ui_ScreenMonitor_Container_tile9, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_ScreenMonitor_Container_tile9, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ScreenMonitor_Container_tile9, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_ScreenMonitor_Container_tile9, lv_color_hex(0x00007F), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_main_stop(ui_ScreenMonitor_Container_tile9, 120, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_stop(ui_ScreenMonitor_Container_tile9, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_dir(ui_ScreenMonitor_Container_tile9, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_ScreenMonitor_Container_tile9, lv_color_hex(0x0000FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_ScreenMonitor_Container_tile9, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_ScreenMonitor_Container_tile9, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ScreenMonitor_Label_tileNumber9 = lv_label_create(ui_ScreenMonitor_Container_tile9);
lv_obj_set_width( ui_ScreenMonitor_Label_tileNumber9, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ScreenMonitor_Label_tileNumber9, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ScreenMonitor_Label_tileNumber9, 0 );
lv_obj_set_y( ui_ScreenMonitor_Label_tileNumber9, 8 );
lv_obj_set_align( ui_ScreenMonitor_Label_tileNumber9, LV_ALIGN_CENTER );
lv_label_set_text(ui_ScreenMonitor_Label_tileNumber9,"0");

ui_ScreenMonitor_Label_tilePid9 = lv_label_create(ui_ScreenMonitor_Container_tile9);
lv_obj_set_width( ui_ScreenMonitor_Label_tilePid9, lv_pct(100));
lv_obj_set_height( ui_ScreenMonitor_Label_tilePid9, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_ScreenMonitor_Label_tilePid9, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_ScreenMonitor_Label_tilePid9,"-");
lv_obj_set_style_text_color(ui_ScreenMonitor_Label_tilePid9, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ScreenMonitor_Label_tilePid9, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_ScreenMonitor_Label_tilePid9, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_ScreenMonitor_Label_tilePid9, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_ScreenMonitor_Label_tilePid9, lv_color_hex(0xFE65FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ScreenMonitor_Label_tilePid9, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ScreenMonitor_Label_tileUnit9 = lv_label_create(ui_ScreenMonitor_Container_tile9);
lv_obj_set_width( ui_ScreenMonitor_Label_tileUnit9, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ScreenMonitor_Label_tileUnit9, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_ScreenMonitor_Label_tileUnit9, LV_ALIGN_BOTTOM_MID );
lv_label_set_text(ui_ScreenMonitor_Label_tileUnit9,"-");
lv_obj_set_style_text_color(ui_ScreenMonitor_Label_tileUnit9, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ScreenMonitor_Label_tileUnit9, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_ScreenMonitor_Label_tileUnit9, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ScreenMonitor_Button_swipeLeft = lv_btn_create(ui_Screen_ScreenMonitor);
lv_obj_set_width( ui_ScreenMonitor_Button_swipeLeft, 36);
lv_obj_set_height( ui_ScreenMonitor_Button_swipeLeft, 36);
lv_obj_set_align( ui_ScreenMonitor_Button_swipeLeft, LV_ALIGN_LEFT_MID );
lv_obj_add_flag( ui_ScreenMonitor_Button_swipeLeft, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ScreenMonitor_Button_swipeLeft, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ScreenMonitor_Button_swipeLeft, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ScreenMonitor_Button_swipeLeft, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_ScreenMonitor_Button_swipeLeft, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_ScreenMonitor_Button_swipeLeft, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ScreenMonitor_Label_left = lv_label_create(ui_ScreenMonitor_Button_swipeLeft);
lv_obj_set_width( ui_ScreenMonitor_Label_left, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ScreenMonitor_Label_left, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_ScreenMonitor_Label_left, LV_ALIGN_CENTER );
lv_label_set_text(ui_ScreenMonitor_Label_left,"<");
lv_obj_set_style_text_color(ui_ScreenMonitor_Label_left, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ScreenMonitor_Label_left, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_ScreenMonitor_Label_left, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_ScreenMonitor_Label_left, &lv_font_montserrat_38, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ScreenMonitor_Label_info2 = lv_label_create(ui_Screen_ScreenMonitor);
lv_obj_set_width( ui_ScreenMonitor_Label_info2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ScreenMonitor_Label_info2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_ScreenMonitor_Label_info2, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_ScreenMonitor_Label_info2,"");
lv_obj_set_style_text_color(ui_ScreenMonitor_Label_info2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ScreenMonitor_Label_info2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_ScreenMonitor_Label_info2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_ScreenMonitor_Label_info2, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_ScreenMonitor_Label_info2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ScreenMonitor_Label_info2, 180, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_ScreenMonitor_Button_swipeLeft, ui_event_ScreenMonitor_Button_swipeLeft, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Screen_ScreenMonitor, ui_event_Screen_ScreenMonitor, LV_EVENT_ALL, NULL);

}

void ui_Screen_ScreenMonitor_screen_destroy(void)
{
   if (ui_Screen_ScreenMonitor) lv_obj_del(ui_Screen_ScreenMonitor);

// NULL screen variables
ui_Screen_ScreenMonitor= NULL;
ui_ScreenMonitor_Container_tile1= NULL;
ui_ScreenMonitor_Label_tileNumber1= NULL;
ui_ScreenMonitor_Label_tilePid1= NULL;
ui_ScreenMonitor_Label_tileUnit1= NULL;
ui_ScreenMonitor_Container_tile2= NULL;
ui_ScreenMonitor_Label_tileNumber2= NULL;
ui_ScreenMonitor_Label_tilePid2= NULL;
ui_ScreenMonitor_Label_tileUnit2= NULL;
ui_ScreenMonitor_Container_tile3= NULL;
ui_ScreenMonitor_Label_tileNumber3= NULL;
ui_ScreenMonitor_Label_tilePid3= NULL;
ui_ScreenMonitor_Label_tileUnit3= NULL;
ui_ScreenMonitor_Container_tile4= NULL;
ui_ScreenMonitor_Label_tileNumber4= NULL;
ui_ScreenMonitor_Label_tilePid4= NULL;
ui_ScreenMonitor_Label_tileUnit4= NULL;
ui_ScreenMonitor_Container_tile5= NULL;
ui_ScreenMonitor_Label_tileNumber5= NULL;
ui_ScreenMonitor_Label_tilePid5= NULL;
ui_ScreenMonitor_Label_tileUnit5= NULL;
ui_ScreenMonitor_Container_tile6= NULL;
ui_ScreenMonitor_Label_tileNumber6= NULL;
ui_ScreenMonitor_Label_tilePid6= NULL;
ui_ScreenMonitor_Label_tileUnit6= NULL;
ui_ScreenMonitor_Container_tile7= NULL;
ui_ScreenMonitor_Label_tileNumber7= NULL;
ui_ScreenMonitor_Label_tilePid7= NULL;
ui_ScreenMonitor_Label_tileUnit7= NULL;
ui_ScreenMonitor_Container_tile8= NULL;
ui_ScreenMonitor_Label_tileNumber8= NULL;
ui_ScreenMonitor_Label_tilePid8= NULL;
ui_ScreenMonitor_Label_tileUnit8= NULL;
ui_ScreenMonitor_Container_tile9= NULL;
ui_ScreenMonitor_Label_tileNumber9= NULL;
ui_ScreenMonitor_Label_tilePid9= NULL;
ui_ScreenMonitor_Label_tileUnit9= NULL;
ui_ScreenMonitor_Button_swipeLeft= NULL;
ui_ScreenMonitor_Label_left= NULL;
ui_ScreenMonitor_Label_info2= NULL;

}
