// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: obd2_gauge_catalyst

#include "ui.h"

lv_obj_t *ui_Screen_ScreenConfig = NULL;lv_obj_t *ui_ScreenConfig_Tabview_Config = NULL;lv_obj_t *ui_ScreenConfig_Tabpage_Setting = NULL;lv_obj_t *ui_ScreenConfig_Label_Label3 = NULL;lv_obj_t *ui_ScreenConfig_Slider_Brightness = NULL;lv_obj_t *ui_ScreenConfig_Slider_Volume = NULL;lv_obj_t *ui_ScreenConfig_Switch_Sleep = NULL;lv_obj_t *ui_ScreenConfig_Switch_Info = NULL;lv_obj_t *ui_ScreenConfig_Image_Moon = NULL;lv_obj_t *ui_ScreenConfig_Image_Sun = NULL;lv_obj_t *ui_ScreenConfig_Button_customPID = NULL;lv_obj_t *ui_ScreenConfig_Label_custom = NULL;lv_obj_t *ui_ScreenConfig_Button_saveConfig = NULL;lv_obj_t *ui_ScreenConfig_Label_Save = NULL;lv_obj_t *ui_ScreenConfig_Dropdown_fontStyle = NULL;lv_obj_t *ui_ScreenConfig_Dropdown_threshold = NULL;lv_obj_t *ui_ScreenConfig_Tabpage_About = NULL;lv_obj_t *ui_ScreenConfig_Label_Label4 = NULL;lv_obj_t *ui_ScreenConfig_Label_aboutText = NULL;lv_obj_t *ui_ScreenConfig_Label_activateStatus = NULL;lv_obj_t *ui_ScreenConfig_Container_animation = NULL;lv_obj_t *ui_ScreenConfig_Tabpage_Activate = NULL;lv_obj_t *ui_ScreenConfig_Container_Container8 = NULL;lv_obj_t *ui_ScreenConfig_Textarea_activationCode = NULL;lv_obj_t *ui_ScreenConfig_Button_activate = NULL;lv_obj_t *ui_ScreenConfig_Label_activateLabel = NULL;lv_obj_t *ui_ScreenConfig_Label_Label12 = NULL;lv_obj_t *ui_ScreenConfig_Label_Label11 = NULL;lv_obj_t *ui_ScreenConfig_Image_qrcode = NULL;lv_obj_t *ui_ScreenConfig_Keyboard_keypad = NULL;lv_obj_t *ui_ScreenConfig_Tabpage_Terminal = NULL;lv_obj_t *ui_ScreenConfig_Textarea_Terminal = NULL;lv_obj_t *ui_ScreenConfig_Button_swipeDown = NULL;lv_obj_t *ui_ScreenConfig_Label_down = NULL;
// event funtions
void ui_event_Screen_ScreenConfig( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_TOP  ) {
lv_indev_wait_release(lv_indev_get_act());
      _ui_screen_change( &ui_Screen_ScreenGauge, LV_SCR_LOAD_ANIM_MOVE_TOP, 500, 0, &ui_Screen_ScreenGauge_screen_init);
      changeScreenGauge( e );
}
}

void ui_event_ScreenConfig_Tabview_Config( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_VALUE_CHANGED) {
      setupTabChanged( e );
}
}

void ui_event_ScreenConfig_Slider_Brightness( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_VALUE_CHANGED) {
      setBrightness( e );
}
}

void ui_event_ScreenConfig_Slider_Volume( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_VALUE_CHANGED) {
      setVolume( e );
}
}

void ui_event_ScreenConfig_Switch_Sleep( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);

if ( event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target,LV_STATE_CHECKED)  ) {
      autoPowerOffEnable( e );
}
if ( event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target,LV_STATE_CHECKED)  ) {
      autoPowerOffDisable( e );
}
}

void ui_event_ScreenConfig_Switch_Info( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);

if ( event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target,LV_STATE_CHECKED)  ) {
      showSystemInfo( e );
}
if ( event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target,LV_STATE_CHECKED)  ) {
      hideSystemInfo( e );
}
}

void ui_event_ScreenConfig_Button_customPID( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      loadCustomPid( e );
}
}

void ui_event_ScreenConfig_Button_saveConfig( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      saveConfig( e );
}
}

void ui_event_ScreenConfig_Dropdown_fontStyle( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_VALUE_CHANGED) {
      changeFont( e );
}
}

void ui_event_ScreenConfig_Dropdown_threshold( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_VALUE_CHANGED) {
      changeFont( e );
}
}

void ui_event_ScreenConfig_Textarea_activationCode( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_flag_modify( ui_ScreenConfig_Keyboard_keypad, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
}
}

void ui_event_ScreenConfig_Button_activate( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      activate( e );
      _ui_flag_modify( ui_ScreenConfig_Keyboard_keypad, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
}

void ui_event_ScreenConfig_Keyboard_keypad( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_VALUE_CHANGED) {
      readKeyboard( e );
}
}

void ui_event_ScreenConfig_Button_swipeDown( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Screen_ScreenGauge, LV_SCR_LOAD_ANIM_MOVE_TOP, 500, 0, &ui_Screen_ScreenGauge_screen_init);
      changeScreenGauge( e );
}
}

// build funtions

void ui_Screen_ScreenConfig_screen_init(void)
{
ui_Screen_ScreenConfig = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen_ScreenConfig, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Screen_ScreenConfig, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Screen_ScreenConfig, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ScreenConfig_Tabview_Config = lv_tabview_create(ui_Screen_ScreenConfig, LV_DIR_TOP, 32);
lv_obj_set_width( ui_ScreenConfig_Tabview_Config, lv_pct(100));
lv_obj_set_height( ui_ScreenConfig_Tabview_Config, lv_pct(100));
lv_obj_set_align( ui_ScreenConfig_Tabview_Config, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_ScreenConfig_Tabview_Config, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_bg_color(ui_ScreenConfig_Tabview_Config, lv_color_hex(0x333333), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ScreenConfig_Tabview_Config, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_ScreenConfig_Tabview_Config, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_ScreenConfig_Tabview_Config, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_ScreenConfig_Tabview_Config, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_text_color(lv_tabview_get_tab_btns(ui_ScreenConfig_Tabview_Config), lv_color_hex(0xFFFFFF),  LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(lv_tabview_get_tab_btns(ui_ScreenConfig_Tabview_Config), 255,  LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(lv_tabview_get_tab_btns(ui_ScreenConfig_Tabview_Config), &lv_font_montserrat_14,  LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(lv_tabview_get_tab_btns(ui_ScreenConfig_Tabview_Config), lv_color_hex(0x000000),  LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(lv_tabview_get_tab_btns(ui_ScreenConfig_Tabview_Config), 255,  LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(lv_tabview_get_tab_btns(ui_ScreenConfig_Tabview_Config), lv_color_hex(0x555555),  LV_PART_ITEMS | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(lv_tabview_get_tab_btns(ui_ScreenConfig_Tabview_Config), 255,  LV_PART_ITEMS| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(lv_tabview_get_tab_btns(ui_ScreenConfig_Tabview_Config), lv_color_hex(0x222222),  LV_PART_ITEMS | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(lv_tabview_get_tab_btns(ui_ScreenConfig_Tabview_Config), LV_GRAD_DIR_VER,  LV_PART_ITEMS| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(lv_tabview_get_tab_btns(ui_ScreenConfig_Tabview_Config), lv_color_hex(0xCCCCCC),  LV_PART_ITEMS | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(lv_tabview_get_tab_btns(ui_ScreenConfig_Tabview_Config), 255,  LV_PART_ITEMS| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(lv_tabview_get_tab_btns(ui_ScreenConfig_Tabview_Config), 2,  LV_PART_ITEMS| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(lv_tabview_get_tab_btns(ui_ScreenConfig_Tabview_Config), LV_BORDER_SIDE_LEFT,  LV_PART_ITEMS| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(lv_tabview_get_tab_btns(ui_ScreenConfig_Tabview_Config), lv_color_hex(0x222222),  LV_PART_ITEMS | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(lv_tabview_get_tab_btns(ui_ScreenConfig_Tabview_Config), 255,  LV_PART_ITEMS| LV_STATE_DEFAULT);
lv_obj_set_style_outline_width(lv_tabview_get_tab_btns(ui_ScreenConfig_Tabview_Config), 4,  LV_PART_ITEMS| LV_STATE_DEFAULT);
lv_obj_set_style_outline_pad(lv_tabview_get_tab_btns(ui_ScreenConfig_Tabview_Config), 0,  LV_PART_ITEMS| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(lv_tabview_get_tab_btns(ui_ScreenConfig_Tabview_Config), lv_color_hex(0x000000),  LV_PART_ITEMS | LV_STATE_CHECKED );
lv_obj_set_style_text_opa(lv_tabview_get_tab_btns(ui_ScreenConfig_Tabview_Config), 255,  LV_PART_ITEMS| LV_STATE_CHECKED);
lv_obj_set_style_bg_color(lv_tabview_get_tab_btns(ui_ScreenConfig_Tabview_Config), lv_color_hex(0xFFFFFF),  LV_PART_ITEMS | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(lv_tabview_get_tab_btns(ui_ScreenConfig_Tabview_Config), 255,  LV_PART_ITEMS| LV_STATE_CHECKED);
lv_obj_set_style_bg_grad_dir(lv_tabview_get_tab_btns(ui_ScreenConfig_Tabview_Config), LV_GRAD_DIR_NONE,  LV_PART_ITEMS| LV_STATE_CHECKED);
lv_obj_set_style_border_color(lv_tabview_get_tab_btns(ui_ScreenConfig_Tabview_Config), lv_color_hex(0x735A02),  LV_PART_ITEMS | LV_STATE_CHECKED );
lv_obj_set_style_border_opa(lv_tabview_get_tab_btns(ui_ScreenConfig_Tabview_Config), 255,  LV_PART_ITEMS| LV_STATE_CHECKED);
lv_obj_set_style_border_width(lv_tabview_get_tab_btns(ui_ScreenConfig_Tabview_Config), 7,  LV_PART_ITEMS| LV_STATE_CHECKED);
lv_obj_set_style_border_side(lv_tabview_get_tab_btns(ui_ScreenConfig_Tabview_Config), LV_BORDER_SIDE_RIGHT,  LV_PART_ITEMS| LV_STATE_CHECKED);
lv_obj_set_style_outline_color(lv_tabview_get_tab_btns(ui_ScreenConfig_Tabview_Config), lv_color_hex(0xFFA100),  LV_PART_ITEMS | LV_STATE_CHECKED );
lv_obj_set_style_outline_opa(lv_tabview_get_tab_btns(ui_ScreenConfig_Tabview_Config), 255,  LV_PART_ITEMS| LV_STATE_CHECKED);
lv_obj_set_style_outline_width(lv_tabview_get_tab_btns(ui_ScreenConfig_Tabview_Config), 4,  LV_PART_ITEMS| LV_STATE_CHECKED);
lv_obj_set_style_outline_pad(lv_tabview_get_tab_btns(ui_ScreenConfig_Tabview_Config), -2,  LV_PART_ITEMS| LV_STATE_CHECKED);

ui_ScreenConfig_Tabpage_Setting = lv_tabview_add_tab(ui_ScreenConfig_Tabview_Config, "Setting");
lv_obj_clear_flag( ui_ScreenConfig_Tabpage_Setting, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_scrollbar_mode(ui_ScreenConfig_Tabpage_Setting, LV_SCROLLBAR_MODE_OFF);
lv_obj_set_scroll_dir(ui_ScreenConfig_Tabpage_Setting, LV_DIR_HOR);

ui_ScreenConfig_Label_Label3 = lv_label_create(ui_ScreenConfig_Tabpage_Setting);
lv_obj_set_width( ui_ScreenConfig_Label_Label3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ScreenConfig_Label_Label3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ScreenConfig_Label_Label3, 0 );
lv_obj_set_y( ui_ScreenConfig_Label_Label3, 15 );
lv_obj_set_align( ui_ScreenConfig_Label_Label3, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_ScreenConfig_Label_Label3,"Brightness    -                                                +\nSpeaker Vol   -                                                +\nAuto Sleep                   Info Display\nWake Thres                  Font");
lv_obj_set_style_text_color(ui_ScreenConfig_Label_Label3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ScreenConfig_Label_Label3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_letter_space(ui_ScreenConfig_Label_Label3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_ScreenConfig_Label_Label3, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_ScreenConfig_Label_Label3, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ScreenConfig_Slider_Brightness = lv_slider_create(ui_ScreenConfig_Tabpage_Setting);
lv_slider_set_range(ui_ScreenConfig_Slider_Brightness, 0,200);
lv_slider_set_mode(ui_ScreenConfig_Slider_Brightness, LV_SLIDER_MODE_RANGE);
lv_slider_set_value( ui_ScreenConfig_Slider_Brightness, 150, LV_ANIM_OFF);
if (lv_slider_get_mode(ui_ScreenConfig_Slider_Brightness)==LV_SLIDER_MODE_RANGE ) lv_slider_set_left_value( ui_ScreenConfig_Slider_Brightness, 25, LV_ANIM_OFF);
lv_obj_set_width( ui_ScreenConfig_Slider_Brightness, 180);
lv_obj_set_height( ui_ScreenConfig_Slider_Brightness, 15);
lv_obj_set_x( ui_ScreenConfig_Slider_Brightness, 47 );
lv_obj_set_y( ui_ScreenConfig_Slider_Brightness, -68 );
lv_obj_set_align( ui_ScreenConfig_Slider_Brightness, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_ScreenConfig_Slider_Brightness, LV_OBJ_FLAG_GESTURE_BUBBLE );    /// Flags
lv_obj_set_style_bg_color(ui_ScreenConfig_Slider_Brightness, lv_color_hex(0x330000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ScreenConfig_Slider_Brightness, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_ScreenConfig_Slider_Brightness, lv_color_hex(0x555555), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_ScreenConfig_Slider_Brightness, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_width(ui_ScreenConfig_Slider_Brightness, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_pad(ui_ScreenConfig_Slider_Brightness, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_ScreenConfig_Slider_Brightness, lv_color_hex(0xFF0000), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ScreenConfig_Slider_Brightness, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_ScreenConfig_Slider_Brightness, lv_color_hex(0x330000), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_ScreenConfig_Slider_Brightness, LV_GRAD_DIR_VER, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_ScreenConfig_Slider_Brightness, lv_color_hex(0x555555), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ScreenConfig_Slider_Brightness, 255, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_ScreenConfig_Slider_Brightness, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_ScreenConfig_Slider_Brightness, LV_GRAD_DIR_VER, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_ScreenConfig_Slider_Brightness, lv_color_hex(0x333333), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_ScreenConfig_Slider_Brightness, 255, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_ScreenConfig_Slider_Brightness, 3, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_ScreenConfig_Slider_Volume = lv_slider_create(ui_ScreenConfig_Tabpage_Setting);
lv_slider_set_range(ui_ScreenConfig_Slider_Volume, 10,80);
lv_slider_set_value( ui_ScreenConfig_Slider_Volume, 50, LV_ANIM_OFF);
if (lv_slider_get_mode(ui_ScreenConfig_Slider_Volume)==LV_SLIDER_MODE_RANGE ) lv_slider_set_left_value( ui_ScreenConfig_Slider_Volume, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_ScreenConfig_Slider_Volume, 180);
lv_obj_set_height( ui_ScreenConfig_Slider_Volume, 15);
lv_obj_set_x( ui_ScreenConfig_Slider_Volume, 47 );
lv_obj_set_y( ui_ScreenConfig_Slider_Volume, -32 );
lv_obj_set_align( ui_ScreenConfig_Slider_Volume, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_ScreenConfig_Slider_Volume, LV_OBJ_FLAG_GESTURE_BUBBLE );    /// Flags
lv_obj_set_style_bg_color(ui_ScreenConfig_Slider_Volume, lv_color_hex(0x330000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ScreenConfig_Slider_Volume, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_ScreenConfig_Slider_Volume, lv_color_hex(0x555555), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_ScreenConfig_Slider_Volume, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_width(ui_ScreenConfig_Slider_Volume, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_pad(ui_ScreenConfig_Slider_Volume, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_ScreenConfig_Slider_Volume, lv_color_hex(0xFF0000), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ScreenConfig_Slider_Volume, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_ScreenConfig_Slider_Volume, lv_color_hex(0x330000), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_ScreenConfig_Slider_Volume, LV_GRAD_DIR_VER, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_ScreenConfig_Slider_Volume, lv_color_hex(0x555555), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ScreenConfig_Slider_Volume, 255, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_ScreenConfig_Slider_Volume, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_ScreenConfig_Slider_Volume, LV_GRAD_DIR_VER, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_ScreenConfig_Slider_Volume, lv_color_hex(0x333333), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_ScreenConfig_Slider_Volume, 255, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_ScreenConfig_Slider_Volume, 3, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_ScreenConfig_Switch_Sleep = lv_switch_create(ui_ScreenConfig_Tabpage_Setting);
lv_obj_set_width( ui_ScreenConfig_Switch_Sleep, 50);
lv_obj_set_height( ui_ScreenConfig_Switch_Sleep, 25);
lv_obj_set_x( ui_ScreenConfig_Switch_Sleep, -38 );
lv_obj_set_y( ui_ScreenConfig_Switch_Sleep, 5 );
lv_obj_set_align( ui_ScreenConfig_Switch_Sleep, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_ScreenConfig_Switch_Sleep, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags

lv_obj_set_style_bg_color(ui_ScreenConfig_Switch_Sleep, lv_color_hex(0x330000), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ScreenConfig_Switch_Sleep, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_ScreenConfig_Switch_Sleep, lv_color_hex(0x555555), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_ScreenConfig_Switch_Sleep, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_ScreenConfig_Switch_Sleep, 2, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_ScreenConfig_Switch_Sleep, lv_color_hex(0xFF0000), LV_PART_INDICATOR | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_ScreenConfig_Switch_Sleep, 255, LV_PART_INDICATOR| LV_STATE_CHECKED);

lv_obj_set_style_bg_color(ui_ScreenConfig_Switch_Sleep, lv_color_hex(0x555555), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ScreenConfig_Switch_Sleep, 255, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_ScreenConfig_Switch_Sleep, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_ScreenConfig_Switch_Sleep, LV_GRAD_DIR_VER, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_ScreenConfig_Switch_Sleep, lv_color_hex(0x333333), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_ScreenConfig_Switch_Sleep, 255, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_ScreenConfig_Switch_Sleep, 3, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_ScreenConfig_Switch_Info = lv_switch_create(ui_ScreenConfig_Tabpage_Setting);
lv_obj_set_width( ui_ScreenConfig_Switch_Info, 50);
lv_obj_set_height( ui_ScreenConfig_Switch_Info, 25);
lv_obj_set_x( ui_ScreenConfig_Switch_Info, 124 );
lv_obj_set_y( ui_ScreenConfig_Switch_Info, 5 );
lv_obj_set_align( ui_ScreenConfig_Switch_Info, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_ScreenConfig_Switch_Info, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags

lv_obj_set_style_bg_color(ui_ScreenConfig_Switch_Info, lv_color_hex(0x330000), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ScreenConfig_Switch_Info, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_ScreenConfig_Switch_Info, lv_color_hex(0x555555), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_ScreenConfig_Switch_Info, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_ScreenConfig_Switch_Info, 2, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_ScreenConfig_Switch_Info, lv_color_hex(0xFF0000), LV_PART_INDICATOR | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_ScreenConfig_Switch_Info, 255, LV_PART_INDICATOR| LV_STATE_CHECKED);

lv_obj_set_style_bg_color(ui_ScreenConfig_Switch_Info, lv_color_hex(0x555555), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ScreenConfig_Switch_Info, 255, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_ScreenConfig_Switch_Info, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_ScreenConfig_Switch_Info, LV_GRAD_DIR_VER, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_ScreenConfig_Switch_Info, lv_color_hex(0x333333), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_ScreenConfig_Switch_Info, 255, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_ScreenConfig_Switch_Info, 3, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_ScreenConfig_Image_Moon = lv_img_create(ui_ScreenConfig_Tabpage_Setting);
lv_img_set_src(ui_ScreenConfig_Image_Moon, &ui_img_moon_png);
lv_obj_set_width( ui_ScreenConfig_Image_Moon, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ScreenConfig_Image_Moon, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ScreenConfig_Image_Moon, -28 );
lv_obj_set_y( ui_ScreenConfig_Image_Moon, -10 );
lv_obj_set_align( ui_ScreenConfig_Image_Moon, LV_ALIGN_TOP_MID );
lv_obj_add_flag( ui_ScreenConfig_Image_Moon, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ScreenConfig_Image_Moon, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_ScreenConfig_Image_Sun = lv_img_create(ui_ScreenConfig_Tabpage_Setting);
lv_img_set_src(ui_ScreenConfig_Image_Sun, &ui_img_sun_png);
lv_obj_set_width( ui_ScreenConfig_Image_Sun, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ScreenConfig_Image_Sun, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ScreenConfig_Image_Sun, 121 );
lv_obj_set_y( ui_ScreenConfig_Image_Sun, -10 );
lv_obj_set_align( ui_ScreenConfig_Image_Sun, LV_ALIGN_TOP_MID );
lv_obj_add_flag( ui_ScreenConfig_Image_Sun, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ScreenConfig_Image_Sun, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_ScreenConfig_Button_customPID = lv_btn_create(ui_ScreenConfig_Tabpage_Setting);
lv_obj_set_height( ui_ScreenConfig_Button_customPID, 30);
lv_obj_set_width( ui_ScreenConfig_Button_customPID, LV_SIZE_CONTENT);  /// 1
lv_obj_set_x( ui_ScreenConfig_Button_customPID, -5 );
lv_obj_set_y( ui_ScreenConfig_Button_customPID, 9 );
lv_obj_set_align( ui_ScreenConfig_Button_customPID, LV_ALIGN_BOTTOM_LEFT );
lv_obj_add_flag( ui_ScreenConfig_Button_customPID, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ScreenConfig_Button_customPID, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ScreenConfig_Button_customPID, lv_color_hex(0xFF00E8), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ScreenConfig_Button_customPID, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_ScreenConfig_Button_customPID, lv_color_hex(0x340139), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_ScreenConfig_Button_customPID, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_ScreenConfig_Button_customPID, lv_color_hex(0x555555), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_ScreenConfig_Button_customPID, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_width(ui_ScreenConfig_Button_customPID, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_pad(ui_ScreenConfig_Button_customPID, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_ScreenConfig_Button_customPID, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ScreenConfig_Button_customPID, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_ScreenConfig_Button_customPID, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ScreenConfig_Label_custom = lv_label_create(ui_ScreenConfig_Button_customPID);
lv_obj_set_width( ui_ScreenConfig_Label_custom, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ScreenConfig_Label_custom, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_ScreenConfig_Label_custom, LV_ALIGN_CENTER );
lv_label_set_text(ui_ScreenConfig_Label_custom,"0 Custom PIDs");

ui_ScreenConfig_Button_saveConfig = lv_btn_create(ui_ScreenConfig_Tabpage_Setting);
lv_obj_set_height( ui_ScreenConfig_Button_saveConfig, 30);
lv_obj_set_width( ui_ScreenConfig_Button_saveConfig, LV_SIZE_CONTENT);  /// 1
lv_obj_set_x( ui_ScreenConfig_Button_saveConfig, 60 );
lv_obj_set_y( ui_ScreenConfig_Button_saveConfig, 9 );
lv_obj_set_align( ui_ScreenConfig_Button_saveConfig, LV_ALIGN_BOTTOM_MID );
lv_obj_add_flag( ui_ScreenConfig_Button_saveConfig, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ScreenConfig_Button_saveConfig, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ScreenConfig_Button_saveConfig, lv_color_hex(0x00FF45), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ScreenConfig_Button_saveConfig, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_ScreenConfig_Button_saveConfig, lv_color_hex(0x013909), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_ScreenConfig_Button_saveConfig, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_ScreenConfig_Button_saveConfig, lv_color_hex(0x555555), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_ScreenConfig_Button_saveConfig, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_width(ui_ScreenConfig_Button_saveConfig, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_pad(ui_ScreenConfig_Button_saveConfig, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_ScreenConfig_Button_saveConfig, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ScreenConfig_Button_saveConfig, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_ScreenConfig_Button_saveConfig, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ScreenConfig_Label_Save = lv_label_create(ui_ScreenConfig_Button_saveConfig);
lv_obj_set_width( ui_ScreenConfig_Label_Save, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ScreenConfig_Label_Save, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_ScreenConfig_Label_Save, LV_ALIGN_CENTER );
lv_label_set_text(ui_ScreenConfig_Label_Save,"0 SAVE");

ui_ScreenConfig_Dropdown_fontStyle = lv_dropdown_create(ui_ScreenConfig_Tabpage_Setting);
lv_dropdown_set_options( ui_ScreenConfig_Dropdown_fontStyle, "Classic\nDigital" );
lv_obj_set_width( ui_ScreenConfig_Dropdown_fontStyle, 100);
lv_obj_set_height( ui_ScreenConfig_Dropdown_fontStyle, 30);
lv_obj_set_x( ui_ScreenConfig_Dropdown_fontStyle, 99 );
lv_obj_set_y( ui_ScreenConfig_Dropdown_fontStyle, 41 );
lv_obj_set_align( ui_ScreenConfig_Dropdown_fontStyle, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ScreenConfig_Dropdown_fontStyle, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_set_style_text_color(ui_ScreenConfig_Dropdown_fontStyle, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ScreenConfig_Dropdown_fontStyle, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_ScreenConfig_Dropdown_fontStyle, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_ScreenConfig_Dropdown_fontStyle, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_ScreenConfig_Dropdown_fontStyle, lv_color_hex(0x330000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ScreenConfig_Dropdown_fontStyle, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_ScreenConfig_Dropdown_fontStyle, lv_color_hex(0x555555), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_ScreenConfig_Dropdown_fontStyle, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_ScreenConfig_Dropdown_fontStyle, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_text_color(ui_ScreenConfig_Dropdown_fontStyle, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ScreenConfig_Dropdown_fontStyle, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_text_color(lv_dropdown_get_list(ui_ScreenConfig_Dropdown_fontStyle), lv_color_hex(0xFFFFFF),  LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(lv_dropdown_get_list(ui_ScreenConfig_Dropdown_fontStyle), 255,  LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(lv_dropdown_get_list(ui_ScreenConfig_Dropdown_fontStyle), LV_TEXT_ALIGN_CENTER,  LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(lv_dropdown_get_list(ui_ScreenConfig_Dropdown_fontStyle), &lv_font_montserrat_16,  LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(lv_dropdown_get_list(ui_ScreenConfig_Dropdown_fontStyle), lv_color_hex(0x000055),  LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(lv_dropdown_get_list(ui_ScreenConfig_Dropdown_fontStyle), 255,  LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(lv_dropdown_get_list(ui_ScreenConfig_Dropdown_fontStyle), lv_color_hex(0x555555),  LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(lv_dropdown_get_list(ui_ScreenConfig_Dropdown_fontStyle), 255,  LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(lv_dropdown_get_list(ui_ScreenConfig_Dropdown_fontStyle), 2,  LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_text_color(lv_dropdown_get_list(ui_ScreenConfig_Dropdown_fontStyle), lv_color_hex(0xFFFFFF),  LV_PART_SELECTED | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(lv_dropdown_get_list(ui_ScreenConfig_Dropdown_fontStyle), 255,  LV_PART_SELECTED| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(lv_dropdown_get_list(ui_ScreenConfig_Dropdown_fontStyle), lv_color_hex(0xFF0000),  LV_PART_SELECTED | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(lv_dropdown_get_list(ui_ScreenConfig_Dropdown_fontStyle), 255,  LV_PART_SELECTED| LV_STATE_DEFAULT);

ui_ScreenConfig_Dropdown_threshold = lv_dropdown_create(ui_ScreenConfig_Tabpage_Setting);
lv_dropdown_set_options( ui_ScreenConfig_Dropdown_threshold, "0.3\n0.5\n1.0" );
lv_obj_set_width( ui_ScreenConfig_Dropdown_threshold, 60);
lv_obj_set_height( ui_ScreenConfig_Dropdown_threshold, 30);
lv_obj_set_x( ui_ScreenConfig_Dropdown_threshold, -32 );
lv_obj_set_y( ui_ScreenConfig_Dropdown_threshold, 41 );
lv_obj_set_align( ui_ScreenConfig_Dropdown_threshold, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ScreenConfig_Dropdown_threshold, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_set_style_text_color(ui_ScreenConfig_Dropdown_threshold, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ScreenConfig_Dropdown_threshold, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_ScreenConfig_Dropdown_threshold, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_ScreenConfig_Dropdown_threshold, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_ScreenConfig_Dropdown_threshold, lv_color_hex(0x330000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ScreenConfig_Dropdown_threshold, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_ScreenConfig_Dropdown_threshold, lv_color_hex(0x555555), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_ScreenConfig_Dropdown_threshold, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_ScreenConfig_Dropdown_threshold, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_text_color(ui_ScreenConfig_Dropdown_threshold, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ScreenConfig_Dropdown_threshold, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_text_color(lv_dropdown_get_list(ui_ScreenConfig_Dropdown_threshold), lv_color_hex(0xFFFFFF),  LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(lv_dropdown_get_list(ui_ScreenConfig_Dropdown_threshold), 255,  LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(lv_dropdown_get_list(ui_ScreenConfig_Dropdown_threshold), LV_TEXT_ALIGN_CENTER,  LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(lv_dropdown_get_list(ui_ScreenConfig_Dropdown_threshold), &lv_font_montserrat_16,  LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(lv_dropdown_get_list(ui_ScreenConfig_Dropdown_threshold), lv_color_hex(0x000055),  LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(lv_dropdown_get_list(ui_ScreenConfig_Dropdown_threshold), 255,  LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(lv_dropdown_get_list(ui_ScreenConfig_Dropdown_threshold), lv_color_hex(0x555555),  LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(lv_dropdown_get_list(ui_ScreenConfig_Dropdown_threshold), 255,  LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(lv_dropdown_get_list(ui_ScreenConfig_Dropdown_threshold), 2,  LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_text_color(lv_dropdown_get_list(ui_ScreenConfig_Dropdown_threshold), lv_color_hex(0xFFFFFF),  LV_PART_SELECTED | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(lv_dropdown_get_list(ui_ScreenConfig_Dropdown_threshold), 255,  LV_PART_SELECTED| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(lv_dropdown_get_list(ui_ScreenConfig_Dropdown_threshold), lv_color_hex(0xFF0000),  LV_PART_SELECTED | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(lv_dropdown_get_list(ui_ScreenConfig_Dropdown_threshold), 255,  LV_PART_SELECTED| LV_STATE_DEFAULT);

ui_ScreenConfig_Tabpage_About = lv_tabview_add_tab(ui_ScreenConfig_Tabview_Config, "About");
lv_obj_clear_flag( ui_ScreenConfig_Tabpage_About, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_scrollbar_mode(ui_ScreenConfig_Tabpage_About, LV_SCROLLBAR_MODE_OFF);
lv_obj_set_scroll_dir(ui_ScreenConfig_Tabpage_About, LV_DIR_HOR);

ui_ScreenConfig_Label_Label4 = lv_label_create(ui_ScreenConfig_Tabpage_About);
lv_obj_set_width( ui_ScreenConfig_Label_Label4, 319);
lv_obj_set_height( ui_ScreenConfig_Label_Label4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ScreenConfig_Label_Label4, 0 );
lv_obj_set_y( ui_ScreenConfig_Label_Label4, -13 );
lv_obj_set_align( ui_ScreenConfig_Label_Label4, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_ScreenConfig_Label_Label4,"OBD-II Gauge Catalyst");
lv_obj_set_style_text_color(ui_ScreenConfig_Label_Label4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ScreenConfig_Label_Label4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_ScreenConfig_Label_Label4, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_ScreenConfig_Label_Label4, &lv_font_montserrat_22, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_ScreenConfig_Label_Label4, lv_color_hex(0xE1FF00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ScreenConfig_Label_Label4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_ScreenConfig_Label_Label4, lv_color_hex(0xFE9600), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_ScreenConfig_Label_Label4, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ScreenConfig_Label_aboutText = lv_label_create(ui_ScreenConfig_Tabpage_About);
lv_obj_set_width( ui_ScreenConfig_Label_aboutText, lv_pct(100));
lv_obj_set_height( ui_ScreenConfig_Label_aboutText, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ScreenConfig_Label_aboutText, 0 );
lv_obj_set_y( ui_ScreenConfig_Label_aboutText, 15 );
lv_obj_set_align( ui_ScreenConfig_Label_aboutText, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_ScreenConfig_Label_aboutText,"VIN        :\nBUILD   :\nSERIAL  :\nSTATUS :");
lv_obj_clear_flag( ui_ScreenConfig_Label_aboutText, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_scrollbar_mode(ui_ScreenConfig_Label_aboutText, LV_SCROLLBAR_MODE_OFF);
lv_obj_set_style_text_color(ui_ScreenConfig_Label_aboutText, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ScreenConfig_Label_aboutText, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_letter_space(ui_ScreenConfig_Label_aboutText, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_ScreenConfig_Label_aboutText, 7, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_ScreenConfig_Label_aboutText, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_ScreenConfig_Label_aboutText, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_ScreenConfig_Label_aboutText, lv_color_hex(0xFF041F), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_ScreenConfig_Label_aboutText, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_ScreenConfig_Label_aboutText, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_ScreenConfig_Label_aboutText, LV_BORDER_SIDE_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ScreenConfig_Label_activateStatus = lv_label_create(ui_ScreenConfig_Tabpage_About);
lv_obj_set_width( ui_ScreenConfig_Label_activateStatus, LV_SIZE_CONTENT);  /// 210
lv_obj_set_height( ui_ScreenConfig_Label_activateStatus, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ScreenConfig_Label_activateStatus, 13 );
lv_obj_set_y( ui_ScreenConfig_Label_activateStatus, 85 );
lv_obj_set_align( ui_ScreenConfig_Label_activateStatus, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_ScreenConfig_Label_activateStatus,"Device is not activated");
lv_obj_set_scrollbar_mode(ui_ScreenConfig_Label_activateStatus, LV_SCROLLBAR_MODE_OFF);
lv_obj_set_style_text_color(ui_ScreenConfig_Label_activateStatus, lv_color_hex(0xFD0018), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ScreenConfig_Label_activateStatus, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_ScreenConfig_Label_activateStatus, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_ScreenConfig_Label_activateStatus, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ScreenConfig_Label_activateStatus, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ScreenConfig_Container_animation = lv_obj_create(ui_ScreenConfig_Tabpage_About);
lv_obj_remove_style_all(ui_ScreenConfig_Container_animation);
lv_obj_set_width( ui_ScreenConfig_Container_animation, 320);
lv_obj_set_height( ui_ScreenConfig_Container_animation, 86);
lv_obj_set_x( ui_ScreenConfig_Container_animation, 0 );
lv_obj_set_y( ui_ScreenConfig_Container_animation, 13 );
lv_obj_set_align( ui_ScreenConfig_Container_animation, LV_ALIGN_BOTTOM_MID );
lv_obj_clear_flag( ui_ScreenConfig_Container_animation, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_img_src( ui_ScreenConfig_Container_animation, &ui_img_thailand_png, LV_PART_MAIN | LV_STATE_DEFAULT );

ui_ScreenConfig_Tabpage_Activate = lv_tabview_add_tab(ui_ScreenConfig_Tabview_Config, "Activate");
lv_obj_clear_flag( ui_ScreenConfig_Tabpage_Activate, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_scrollbar_mode(ui_ScreenConfig_Tabpage_Activate, LV_SCROLLBAR_MODE_OFF);

ui_ScreenConfig_Container_Container8 = lv_obj_create(ui_ScreenConfig_Tabpage_Activate);
lv_obj_remove_style_all(ui_ScreenConfig_Container_Container8);
lv_obj_set_width( ui_ScreenConfig_Container_Container8, 310);
lv_obj_set_height( ui_ScreenConfig_Container_Container8, 107);
lv_obj_set_x( ui_ScreenConfig_Container_Container8, 0 );
lv_obj_set_y( ui_ScreenConfig_Container_Container8, 11 );
lv_obj_set_align( ui_ScreenConfig_Container_Container8, LV_ALIGN_BOTTOM_MID );
lv_obj_clear_flag( ui_ScreenConfig_Container_Container8, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_border_width(ui_ScreenConfig_Container_Container8, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_ScreenConfig_Container_Container8, lv_color_hex(0x2005F7), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_ScreenConfig_Container_Container8, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_width(ui_ScreenConfig_Container_Container8, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_pad(ui_ScreenConfig_Container_Container8, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ScreenConfig_Textarea_activationCode = lv_textarea_create(ui_ScreenConfig_Container_Container8);
lv_obj_set_width( ui_ScreenConfig_Textarea_activationCode, lv_pct(100));
lv_obj_set_height( ui_ScreenConfig_Textarea_activationCode, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ScreenConfig_Textarea_activationCode, 0 );
lv_obj_set_y( ui_ScreenConfig_Textarea_activationCode, 8 );
lv_obj_set_align( ui_ScreenConfig_Textarea_activationCode, LV_ALIGN_TOP_MID );
lv_textarea_set_accepted_chars(ui_ScreenConfig_Textarea_activationCode, "0123456789ABCDEF");
lv_textarea_set_max_length(ui_ScreenConfig_Textarea_activationCode,16);
lv_textarea_set_placeholder_text(ui_ScreenConfig_Textarea_activationCode,"Click here to enter 16 digit hexagonal number");
lv_textarea_set_one_line(ui_ScreenConfig_Textarea_activationCode,true);
lv_obj_clear_flag( ui_ScreenConfig_Textarea_activationCode, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_scrollbar_mode(ui_ScreenConfig_Textarea_activationCode, LV_SCROLLBAR_MODE_OFF);
lv_obj_set_style_text_color(ui_ScreenConfig_Textarea_activationCode, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ScreenConfig_Textarea_activationCode, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_ScreenConfig_Textarea_activationCode, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_ScreenConfig_Textarea_activationCode, &ui_font_oswald_36, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_ScreenConfig_Textarea_activationCode, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ScreenConfig_Textarea_activationCode, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_ScreenConfig_Textarea_activationCode, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_ScreenConfig_Textarea_activationCode, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_border_color(ui_ScreenConfig_Textarea_activationCode, lv_color_hex(0xFFFFFF), LV_PART_CURSOR | LV_STATE_FOCUSED );
lv_obj_set_style_border_opa(ui_ScreenConfig_Textarea_activationCode, 255, LV_PART_CURSOR| LV_STATE_FOCUSED);
lv_obj_set_style_border_width(ui_ScreenConfig_Textarea_activationCode, 2, LV_PART_CURSOR| LV_STATE_FOCUSED);
lv_obj_set_style_border_side(ui_ScreenConfig_Textarea_activationCode, LV_BORDER_SIDE_LEFT, LV_PART_CURSOR| LV_STATE_FOCUSED);

lv_obj_set_style_text_color(ui_ScreenConfig_Textarea_activationCode, lv_color_hex(0x555555), LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ScreenConfig_Textarea_activationCode, 255, LV_PART_TEXTAREA_PLACEHOLDER| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_ScreenConfig_Textarea_activationCode, LV_TEXT_ALIGN_LEFT, LV_PART_TEXTAREA_PLACEHOLDER| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_ScreenConfig_Textarea_activationCode, &lv_font_montserrat_12, LV_PART_TEXTAREA_PLACEHOLDER| LV_STATE_DEFAULT);

ui_ScreenConfig_Button_activate = lv_btn_create(ui_ScreenConfig_Container_Container8);
lv_obj_set_height( ui_ScreenConfig_Button_activate, 27);
lv_obj_set_width( ui_ScreenConfig_Button_activate, LV_SIZE_CONTENT);  /// 75
lv_obj_set_x( ui_ScreenConfig_Button_activate, 0 );
lv_obj_set_y( ui_ScreenConfig_Button_activate, 1 );
lv_obj_set_align( ui_ScreenConfig_Button_activate, LV_ALIGN_BOTTOM_MID );
lv_obj_add_flag( ui_ScreenConfig_Button_activate, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ScreenConfig_Button_activate, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ScreenConfig_Button_activate, lv_color_hex(0x00FF45), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ScreenConfig_Button_activate, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_ScreenConfig_Button_activate, lv_color_hex(0x1A381F), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_ScreenConfig_Button_activate, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_ScreenConfig_Button_activate, lv_color_hex(0x555555), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_ScreenConfig_Button_activate, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_width(ui_ScreenConfig_Button_activate, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_pad(ui_ScreenConfig_Button_activate, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_ScreenConfig_Button_activate, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_ScreenConfig_Button_activate, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_ScreenConfig_Button_activate, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ScreenConfig_Label_activateLabel = lv_label_create(ui_ScreenConfig_Button_activate);
lv_obj_set_width( ui_ScreenConfig_Label_activateLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ScreenConfig_Label_activateLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_ScreenConfig_Label_activateLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_ScreenConfig_Label_activateLabel,"Activate");
lv_obj_set_style_text_color(ui_ScreenConfig_Label_activateLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ScreenConfig_Label_activateLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ScreenConfig_Label_Label12 = lv_label_create(ui_ScreenConfig_Container_Container8);
lv_obj_set_width( ui_ScreenConfig_Label_Label12, lv_pct(103));
lv_obj_set_height( ui_ScreenConfig_Label_Label12, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ScreenConfig_Label_Label12, 0 );
lv_obj_set_y( ui_ScreenConfig_Label_Label12, -4 );
lv_obj_set_align( ui_ScreenConfig_Label_Label12, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_ScreenConfig_Label_Label12,"Click textbox below to enter Activation Code");
lv_obj_set_style_text_color(ui_ScreenConfig_Label_Label12, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ScreenConfig_Label_Label12, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_ScreenConfig_Label_Label12, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_ScreenConfig_Label_Label12, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_ScreenConfig_Label_Label12, lv_color_hex(0x0000FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ScreenConfig_Label_Label12, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_ScreenConfig_Label_Label12, lv_color_hex(0x030951), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_ScreenConfig_Label_Label12, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ScreenConfig_Label_Label11 = lv_label_create(ui_ScreenConfig_Tabpage_Activate);
lv_obj_set_width( ui_ScreenConfig_Label_Label11, 230);
lv_obj_set_height( ui_ScreenConfig_Label_Label11, 85);
lv_obj_set_x( ui_ScreenConfig_Label_Label11, -10 );
lv_obj_set_y( ui_ScreenConfig_Label_Label11, -5 );
lv_label_set_text(ui_ScreenConfig_Label_Label11,"Scan QR: Go to website\n- Install/Update Firmware\n- Donate & get activation code\n- Instructions");
lv_obj_set_style_text_color(ui_ScreenConfig_Label_Label11, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ScreenConfig_Label_Label11, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_letter_space(ui_ScreenConfig_Label_Label11, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_ScreenConfig_Label_Label11, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_ScreenConfig_Label_Label11, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_ScreenConfig_Label_Label11, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_ScreenConfig_Label_Label11, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_ScreenConfig_Label_Label11, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_ScreenConfig_Label_Label11, LV_BORDER_SIDE_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ScreenConfig_Image_qrcode = lv_img_create(ui_ScreenConfig_Tabpage_Activate);
lv_img_set_src(ui_ScreenConfig_Image_qrcode, &ui_img_qrcode_png);
lv_obj_set_width( ui_ScreenConfig_Image_qrcode, 80);
lv_obj_set_height( ui_ScreenConfig_Image_qrcode, 80);
lv_obj_set_x( ui_ScreenConfig_Image_qrcode, 10 );
lv_obj_set_y( ui_ScreenConfig_Image_qrcode, -5 );
lv_obj_set_align( ui_ScreenConfig_Image_qrcode, LV_ALIGN_TOP_RIGHT );
lv_obj_add_flag( ui_ScreenConfig_Image_qrcode, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ScreenConfig_Image_qrcode, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_ScreenConfig_Keyboard_keypad = lv_keyboard_create(ui_ScreenConfig_Tabpage_Activate);
lv_keyboard_set_mode(ui_ScreenConfig_Keyboard_keypad,LV_KEYBOARD_MODE_USER_1);
lv_obj_set_width( ui_ScreenConfig_Keyboard_keypad, 320);
lv_obj_set_height( ui_ScreenConfig_Keyboard_keypad, 120);
lv_obj_set_x( ui_ScreenConfig_Keyboard_keypad, 0 );
lv_obj_set_y( ui_ScreenConfig_Keyboard_keypad, -44 );
lv_obj_set_align( ui_ScreenConfig_Keyboard_keypad, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ScreenConfig_Keyboard_keypad, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_clear_flag( ui_ScreenConfig_Keyboard_keypad, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_scrollbar_mode(ui_ScreenConfig_Keyboard_keypad, LV_SCROLLBAR_MODE_OFF);

lv_obj_set_style_bg_color(ui_ScreenConfig_Keyboard_keypad, lv_color_hex(0x555555), LV_PART_ITEMS | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ScreenConfig_Keyboard_keypad, 255, LV_PART_ITEMS| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_ScreenConfig_Keyboard_keypad, lv_color_hex(0x222222), LV_PART_ITEMS | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_ScreenConfig_Keyboard_keypad, LV_GRAD_DIR_VER, LV_PART_ITEMS| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_ScreenConfig_Keyboard_keypad, lv_color_hex(0xF2FF00), LV_PART_ITEMS | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ScreenConfig_Keyboard_keypad, 255, LV_PART_ITEMS| LV_STATE_DEFAULT);

ui_ScreenConfig_Tabpage_Terminal = lv_tabview_add_tab(ui_ScreenConfig_Tabview_Config, "Log");
lv_obj_clear_flag( ui_ScreenConfig_Tabpage_Terminal, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_scrollbar_mode(ui_ScreenConfig_Tabpage_Terminal, LV_SCROLLBAR_MODE_OFF);
lv_obj_set_scroll_dir(ui_ScreenConfig_Tabpage_Terminal, LV_DIR_HOR);

ui_ScreenConfig_Textarea_Terminal = lv_textarea_create(ui_ScreenConfig_Tabpage_Terminal);
lv_obj_set_width( ui_ScreenConfig_Textarea_Terminal, lv_pct(100));
lv_obj_set_height( ui_ScreenConfig_Textarea_Terminal, lv_pct(100));
lv_obj_set_align( ui_ScreenConfig_Textarea_Terminal, LV_ALIGN_CENTER );
lv_textarea_set_max_length(ui_ScreenConfig_Textarea_Terminal,2048);
lv_textarea_set_text(ui_ScreenConfig_Textarea_Terminal,"[  Va&Cob OBD-II Gauge Catalyst ]\n\n");
lv_textarea_set_placeholder_text(ui_ScreenConfig_Textarea_Terminal,"Va&Cob");
lv_obj_add_flag( ui_ScreenConfig_Textarea_Terminal, LV_OBJ_FLAG_SCROLL_ON_FOCUS | LV_OBJ_FLAG_SCROLL_WITH_ARROW );   /// Flags
lv_obj_clear_flag( ui_ScreenConfig_Textarea_Terminal, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLL_ELASTIC );    /// Flags
lv_obj_set_scroll_dir(ui_ScreenConfig_Textarea_Terminal, LV_DIR_VER);
lv_obj_set_style_text_color(ui_ScreenConfig_Textarea_Terminal, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ScreenConfig_Textarea_Terminal, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_letter_space(ui_ScreenConfig_Textarea_Terminal, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_ScreenConfig_Textarea_Terminal, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_ScreenConfig_Textarea_Terminal, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_ScreenConfig_Textarea_Terminal, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ScreenConfig_Textarea_Terminal, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_ScreenConfig_Textarea_Terminal, lv_color_hex(0x555555), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_ScreenConfig_Textarea_Terminal, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_ScreenConfig_Textarea_Terminal, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_border_color(ui_ScreenConfig_Textarea_Terminal, lv_color_hex(0xFFFFFF), LV_PART_CURSOR | LV_STATE_FOCUSED );
lv_obj_set_style_border_opa(ui_ScreenConfig_Textarea_Terminal, 255, LV_PART_CURSOR| LV_STATE_FOCUSED);
lv_obj_set_style_border_side(ui_ScreenConfig_Textarea_Terminal, LV_BORDER_SIDE_BOTTOM, LV_PART_CURSOR| LV_STATE_FOCUSED);

ui_ScreenConfig_Button_swipeDown = lv_btn_create(ui_Screen_ScreenConfig);
lv_obj_set_width( ui_ScreenConfig_Button_swipeDown, 36);
lv_obj_set_height( ui_ScreenConfig_Button_swipeDown, 36);
lv_obj_set_align( ui_ScreenConfig_Button_swipeDown, LV_ALIGN_BOTTOM_RIGHT );
lv_obj_add_flag( ui_ScreenConfig_Button_swipeDown, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ScreenConfig_Button_swipeDown, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ScreenConfig_Button_swipeDown, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ScreenConfig_Button_swipeDown, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_ScreenConfig_Button_swipeDown, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_ScreenConfig_Button_swipeDown, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ScreenConfig_Label_down = lv_label_create(ui_ScreenConfig_Button_swipeDown);
lv_obj_set_width( ui_ScreenConfig_Label_down, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ScreenConfig_Label_down, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_ScreenConfig_Label_down, LV_ALIGN_CENTER );
lv_label_set_text(ui_ScreenConfig_Label_down,"v");
lv_obj_set_style_text_color(ui_ScreenConfig_Label_down, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ScreenConfig_Label_down, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_ScreenConfig_Label_down, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_ScreenConfig_Label_down, &lv_font_montserrat_38, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_ScreenConfig_Slider_Brightness, ui_event_ScreenConfig_Slider_Brightness, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ScreenConfig_Slider_Volume, ui_event_ScreenConfig_Slider_Volume, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ScreenConfig_Switch_Sleep, ui_event_ScreenConfig_Switch_Sleep, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ScreenConfig_Switch_Info, ui_event_ScreenConfig_Switch_Info, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ScreenConfig_Button_customPID, ui_event_ScreenConfig_Button_customPID, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ScreenConfig_Button_saveConfig, ui_event_ScreenConfig_Button_saveConfig, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ScreenConfig_Dropdown_fontStyle, ui_event_ScreenConfig_Dropdown_fontStyle, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ScreenConfig_Dropdown_threshold, ui_event_ScreenConfig_Dropdown_threshold, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ScreenConfig_Textarea_activationCode, ui_event_ScreenConfig_Textarea_activationCode, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ScreenConfig_Button_activate, ui_event_ScreenConfig_Button_activate, LV_EVENT_ALL, NULL);
lv_keyboard_set_textarea(ui_ScreenConfig_Keyboard_keypad,ui_ScreenConfig_Textarea_activationCode);
lv_obj_add_event_cb(ui_ScreenConfig_Keyboard_keypad, ui_event_ScreenConfig_Keyboard_keypad, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ScreenConfig_Tabview_Config, ui_event_ScreenConfig_Tabview_Config, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ScreenConfig_Button_swipeDown, ui_event_ScreenConfig_Button_swipeDown, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Screen_ScreenConfig, ui_event_Screen_ScreenConfig, LV_EVENT_ALL, NULL);

}

void ui_Screen_ScreenConfig_screen_destroy(void)
{
   if (ui_Screen_ScreenConfig) lv_obj_del(ui_Screen_ScreenConfig);

// NULL screen variables
ui_Screen_ScreenConfig= NULL;
ui_ScreenConfig_Tabview_Config= NULL;
ui_ScreenConfig_Tabpage_Setting= NULL;
ui_ScreenConfig_Label_Label3= NULL;
ui_ScreenConfig_Slider_Brightness= NULL;
ui_ScreenConfig_Slider_Volume= NULL;
ui_ScreenConfig_Switch_Sleep= NULL;
ui_ScreenConfig_Switch_Info= NULL;
ui_ScreenConfig_Image_Moon= NULL;
ui_ScreenConfig_Image_Sun= NULL;
ui_ScreenConfig_Button_customPID= NULL;
ui_ScreenConfig_Label_custom= NULL;
ui_ScreenConfig_Button_saveConfig= NULL;
ui_ScreenConfig_Label_Save= NULL;
ui_ScreenConfig_Dropdown_fontStyle= NULL;
ui_ScreenConfig_Dropdown_threshold= NULL;
ui_ScreenConfig_Tabpage_About= NULL;
ui_ScreenConfig_Label_Label4= NULL;
ui_ScreenConfig_Label_aboutText= NULL;
ui_ScreenConfig_Label_activateStatus= NULL;
ui_ScreenConfig_Container_animation= NULL;
ui_ScreenConfig_Tabpage_Activate= NULL;
ui_ScreenConfig_Container_Container8= NULL;
ui_ScreenConfig_Textarea_activationCode= NULL;
ui_ScreenConfig_Button_activate= NULL;
ui_ScreenConfig_Label_activateLabel= NULL;
ui_ScreenConfig_Label_Label12= NULL;
ui_ScreenConfig_Label_Label11= NULL;
ui_ScreenConfig_Image_qrcode= NULL;
ui_ScreenConfig_Keyboard_keypad= NULL;
ui_ScreenConfig_Tabpage_Terminal= NULL;
ui_ScreenConfig_Textarea_Terminal= NULL;
ui_ScreenConfig_Button_swipeDown= NULL;
ui_ScreenConfig_Label_down= NULL;

}
