// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: obd2_gauge_catalyst

#ifndef UI_SCREEN_SCREENCONFIG_H
#define UI_SCREEN_SCREENCONFIG_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen_ScreenConfig
extern void ui_Screen_ScreenConfig_screen_init(void);
extern void ui_Screen_ScreenConfig_screen_destroy(void);
extern void ui_event_Screen_ScreenConfig( lv_event_t * e);
extern lv_obj_t *ui_Screen_ScreenConfig;
extern void ui_event_ScreenConfig_Tabview_Config( lv_event_t * e);
extern lv_obj_t *ui_ScreenConfig_Tabview_Config;
extern lv_obj_t *ui_ScreenConfig_Tabpage_Setting;
extern lv_obj_t *ui_ScreenConfig_Label_Label3;
extern void ui_event_ScreenConfig_Slider_Brightness( lv_event_t * e);
extern lv_obj_t *ui_ScreenConfig_Slider_Brightness;
extern void ui_event_ScreenConfig_Slider_Volume( lv_event_t * e);
extern lv_obj_t *ui_ScreenConfig_Slider_Volume;
extern void ui_event_ScreenConfig_Switch_Sleep( lv_event_t * e);
extern lv_obj_t *ui_ScreenConfig_Switch_Sleep;
extern void ui_event_ScreenConfig_Switch_Info( lv_event_t * e);
extern lv_obj_t *ui_ScreenConfig_Switch_Info;
extern lv_obj_t *ui_ScreenConfig_Image_Moon;
extern lv_obj_t *ui_ScreenConfig_Image_Sun;
extern void ui_event_ScreenConfig_Button_customPID( lv_event_t * e);
extern lv_obj_t *ui_ScreenConfig_Button_customPID;
extern lv_obj_t *ui_ScreenConfig_Label_custom;
extern void ui_event_ScreenConfig_Button_saveConfig( lv_event_t * e);
extern lv_obj_t *ui_ScreenConfig_Button_saveConfig;
extern lv_obj_t *ui_ScreenConfig_Label_Save;
extern void ui_event_ScreenConfig_Dropdown_fontStyle( lv_event_t * e);
extern lv_obj_t *ui_ScreenConfig_Dropdown_fontStyle;
extern void ui_event_ScreenConfig_Dropdown_threshold( lv_event_t * e);
extern lv_obj_t *ui_ScreenConfig_Dropdown_threshold;
extern lv_obj_t *ui_ScreenConfig_Tabpage_About;
extern lv_obj_t *ui_ScreenConfig_Label_Label4;
extern lv_obj_t *ui_ScreenConfig_Label_aboutText;
extern lv_obj_t *ui_ScreenConfig_Label_activateStatus;
extern lv_obj_t *ui_ScreenConfig_Container_animation;
extern lv_obj_t *ui_ScreenConfig_Tabpage_Activate;
extern lv_obj_t *ui_ScreenConfig_Container_Container8;
extern void ui_event_ScreenConfig_Textarea_activationCode( lv_event_t * e);
extern lv_obj_t *ui_ScreenConfig_Textarea_activationCode;
extern void ui_event_ScreenConfig_Button_activate( lv_event_t * e);
extern lv_obj_t *ui_ScreenConfig_Button_activate;
extern lv_obj_t *ui_ScreenConfig_Label_activateLabel;
extern lv_obj_t *ui_ScreenConfig_Label_Label12;
extern lv_obj_t *ui_ScreenConfig_Label_Label11;
extern lv_obj_t *ui_ScreenConfig_Image_qrcode;
extern void ui_event_ScreenConfig_Keyboard_keypad( lv_event_t * e);
extern lv_obj_t *ui_ScreenConfig_Keyboard_keypad;
extern lv_obj_t *ui_ScreenConfig_Tabpage_Terminal;
extern lv_obj_t *ui_ScreenConfig_Textarea_Terminal;
extern void ui_event_ScreenConfig_Button_swipeDown( lv_event_t * e);
extern lv_obj_t *ui_ScreenConfig_Button_swipeDown;
extern lv_obj_t *ui_ScreenConfig_Label_down;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

