// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: obd2_gauge_catalyst

#ifndef UI_SCREEN_SCREENMONITOR_H
#define UI_SCREEN_SCREENMONITOR_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen_ScreenMonitor
extern void ui_Screen_ScreenMonitor_screen_init(void);
extern void ui_Screen_ScreenMonitor_screen_destroy(void);
extern void ui_event_Screen_ScreenMonitor( lv_event_t * e);
extern lv_obj_t *ui_Screen_ScreenMonitor;
extern lv_obj_t *ui_ScreenMonitor_Container_tile1;
extern lv_obj_t *ui_ScreenMonitor_Label_tileNumber1;
extern lv_obj_t *ui_ScreenMonitor_Label_tilePid1;
extern lv_obj_t *ui_ScreenMonitor_Label_tileUnit1;
extern lv_obj_t *ui_ScreenMonitor_Container_tile2;
extern lv_obj_t *ui_ScreenMonitor_Label_tileNumber2;
extern lv_obj_t *ui_ScreenMonitor_Label_tilePid2;
extern lv_obj_t *ui_ScreenMonitor_Label_tileUnit2;
extern lv_obj_t *ui_ScreenMonitor_Container_tile3;
extern lv_obj_t *ui_ScreenMonitor_Label_tileNumber3;
extern lv_obj_t *ui_ScreenMonitor_Label_tilePid3;
extern lv_obj_t *ui_ScreenMonitor_Label_tileUnit3;
extern lv_obj_t *ui_ScreenMonitor_Container_tile4;
extern lv_obj_t *ui_ScreenMonitor_Label_tileNumber4;
extern lv_obj_t *ui_ScreenMonitor_Label_tilePid4;
extern lv_obj_t *ui_ScreenMonitor_Label_tileUnit4;
extern lv_obj_t *ui_ScreenMonitor_Container_tile5;
extern lv_obj_t *ui_ScreenMonitor_Label_tileNumber5;
extern lv_obj_t *ui_ScreenMonitor_Label_tilePid5;
extern lv_obj_t *ui_ScreenMonitor_Label_tileUnit5;
extern lv_obj_t *ui_ScreenMonitor_Container_tile6;
extern lv_obj_t *ui_ScreenMonitor_Label_tileNumber6;
extern lv_obj_t *ui_ScreenMonitor_Label_tilePid6;
extern lv_obj_t *ui_ScreenMonitor_Label_tileUnit6;
extern lv_obj_t *ui_ScreenMonitor_Container_tile7;
extern lv_obj_t *ui_ScreenMonitor_Label_tileNumber7;
extern lv_obj_t *ui_ScreenMonitor_Label_tilePid7;
extern lv_obj_t *ui_ScreenMonitor_Label_tileUnit7;
extern lv_obj_t *ui_ScreenMonitor_Container_tile8;
extern lv_obj_t *ui_ScreenMonitor_Label_tileNumber8;
extern lv_obj_t *ui_ScreenMonitor_Label_tilePid8;
extern lv_obj_t *ui_ScreenMonitor_Label_tileUnit8;
extern lv_obj_t *ui_ScreenMonitor_Container_tile9;
extern lv_obj_t *ui_ScreenMonitor_Label_tileNumber9;
extern lv_obj_t *ui_ScreenMonitor_Label_tilePid9;
extern lv_obj_t *ui_ScreenMonitor_Label_tileUnit9;
extern void ui_event_ScreenMonitor_Button_swipeLeft( lv_event_t * e);
extern lv_obj_t *ui_ScreenMonitor_Button_swipeLeft;
extern lv_obj_t *ui_ScreenMonitor_Label_left;
extern lv_obj_t *ui_ScreenMonitor_Label_info2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

