// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: obd2_gauge_catalyst

#include "ui.h"

lv_obj_t *ui_Screen_ScreenTitle = NULL;
// event funtions
void ui_event_Screen_ScreenTitle( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_SCREEN_LOADED) {
      _ui_screen_change( &ui_Screen_ScreenGauge, LV_SCR_LOAD_ANIM_NONE, 0, 1000, &ui_Screen_ScreenGauge_screen_init);
      sweepDial( e );
}
}

// build funtions

void ui_Screen_ScreenTitle_screen_init(void)
{
ui_Screen_ScreenTitle = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen_ScreenTitle, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_img_src( ui_Screen_ScreenTitle, &ui_img_vaandcob_png, LV_PART_MAIN | LV_STATE_DEFAULT );

lv_obj_add_event_cb(ui_Screen_ScreenTitle, ui_event_Screen_ScreenTitle, LV_EVENT_ALL, NULL);

}

void ui_Screen_ScreenTitle_screen_destroy(void)
{
   if (ui_Screen_ScreenTitle) lv_obj_del(ui_Screen_ScreenTitle);

// NULL screen variables
ui_Screen_ScreenTitle= NULL;

}
