// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: obd2_gauge_catalyst

#ifndef UI_SCREEN_SCREENTITLE_H
#define UI_SCREEN_SCREENTITLE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen_ScreenTitle
extern void ui_Screen_ScreenTitle_screen_init(void);
extern void ui_Screen_ScreenTitle_screen_destroy(void);
extern void ui_event_Screen_ScreenTitle( lv_event_t * e);
extern lv_obj_t *ui_Screen_ScreenTitle;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

