// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: obd2_gauge_catalyst

#include "ui.h"

lv_obj_t *ui_Screen_ScreenService = NULL;lv_obj_t *ui_ScreenService_Tabview_Service = NULL;lv_obj_t *ui_ScreenService_Tabpage_Warning = NULL;lv_obj_t *ui_ScreenService_Roller_warnList = NULL;lv_obj_t *ui_ScreenService_Slider_limit = NULL;lv_obj_t *ui_ScreenService_Label_min = NULL;lv_obj_t *ui_ScreenService_Label_max = NULL;lv_obj_t *ui_ScreenService_Button_saveWarn = NULL;lv_obj_t *ui_ScreenService_Label_Save1 = NULL;lv_obj_t *ui_ScreenService_Button_setDefault = NULL;lv_obj_t *ui_ScreenService_Label_Save2 = NULL;lv_obj_t *ui_ScreenService_Label_warnValue = NULL;lv_obj_t *ui_ScreenService_Tabpage_Diagnostics = NULL;lv_obj_t *ui_ScreenService_Button_readDTC = NULL;lv_obj_t *ui_ScreenService_Label_Label5 = NULL;lv_obj_t *ui_ScreenService_Button_updateDescription = NULL;lv_obj_t *ui_ScreenService_Label_Label10 = NULL;lv_obj_t *ui_ScreenService_Label_pleasewait = NULL;lv_obj_t *ui_ScreenService_Panel_dtc = NULL;lv_obj_t *ui_ScreenService_Button_clearMIL = NULL;lv_obj_t *ui_ScreenService_Label_Label7 = NULL;lv_obj_t *ui_ScreenService_Textarea_DTCList = NULL;lv_obj_t *ui_ScreenService_Label_MILStatus = NULL;lv_obj_t *ui_ScreenService_Button_closeDTC = NULL;lv_obj_t *ui_ScreenService_Label_Label8 = NULL;lv_obj_t *ui_ScreenService_Image_Image1 = NULL;lv_obj_t *ui_ScreenService_Image_Image2 = NULL;lv_obj_t *ui_ScreenService_Button_swipeUp = NULL;lv_obj_t *ui_ScreenService_Label_upup = NULL;
// event funtions
void ui_event_Screen_ScreenService( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_BOTTOM  ) {
lv_indev_wait_release(lv_indev_get_act());
      _ui_screen_change( &ui_Screen_ScreenGauge, LV_SCR_LOAD_ANIM_MOVE_BOTTOM, 500, 0, &ui_Screen_ScreenGauge_screen_init);
      changeScreenGauge( e );
}
}

void ui_event_ScreenService_Tabview_Service( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_VALUE_CHANGED) {
      serviceTabChanged( e );
}
}

void ui_event_ScreenService_Roller_warnList( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_VALUE_CHANGED) {
      loadWarning( e );
      ( e );
}
}

void ui_event_ScreenService_Slider_limit( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_VALUE_CHANGED) {
      setWarningLimit( e );
}
}

void ui_event_ScreenService_Button_readDTC( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      readDTC( e );
}
}

void ui_event_ScreenService_Button_updateDescription( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      updateDTC( e );
}
}

void ui_event_ScreenService_Button_clearMIL( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      confirmClearMIL( e );
}
}

void ui_event_ScreenService_Button_closeDTC( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      abortClearMIL( e );
}
}

void ui_event_ScreenService_Button_swipeUp( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Screen_ScreenGauge, LV_SCR_LOAD_ANIM_MOVE_BOTTOM, 500, 0, &ui_Screen_ScreenGauge_screen_init);
      changeScreenGauge( e );
}
}

// build funtions

void ui_Screen_ScreenService_screen_init(void)
{
ui_Screen_ScreenService = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen_ScreenService, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Screen_ScreenService, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Screen_ScreenService, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_Screen_ScreenService, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Screen_ScreenService, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ScreenService_Tabview_Service = lv_tabview_create(ui_Screen_ScreenService, LV_DIR_BOTTOM, 32);
lv_obj_set_width( ui_ScreenService_Tabview_Service, lv_pct(100));
lv_obj_set_height( ui_ScreenService_Tabview_Service, lv_pct(100));
lv_obj_set_align( ui_ScreenService_Tabview_Service, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_ScreenService_Tabview_Service, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_bg_color(ui_ScreenService_Tabview_Service, lv_color_hex(0x333333), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ScreenService_Tabview_Service, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_ScreenService_Tabview_Service, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_ScreenService_Tabview_Service, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_text_color(lv_tabview_get_tab_btns(ui_ScreenService_Tabview_Service), lv_color_hex(0xFFFFFF),  LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(lv_tabview_get_tab_btns(ui_ScreenService_Tabview_Service), 255,  LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(lv_tabview_get_tab_btns(ui_ScreenService_Tabview_Service), &lv_font_montserrat_16,  LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(lv_tabview_get_tab_btns(ui_ScreenService_Tabview_Service), lv_color_hex(0x000000),  LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(lv_tabview_get_tab_btns(ui_ScreenService_Tabview_Service), 255,  LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(lv_tabview_get_tab_btns(ui_ScreenService_Tabview_Service), lv_color_hex(0x767776),  LV_PART_ITEMS | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(lv_tabview_get_tab_btns(ui_ScreenService_Tabview_Service), 255,  LV_PART_ITEMS| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(lv_tabview_get_tab_btns(ui_ScreenService_Tabview_Service), lv_color_hex(0x0D0D0D),  LV_PART_ITEMS | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(lv_tabview_get_tab_btns(ui_ScreenService_Tabview_Service), LV_GRAD_DIR_VER,  LV_PART_ITEMS| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(lv_tabview_get_tab_btns(ui_ScreenService_Tabview_Service), lv_color_hex(0x000000),  LV_PART_ITEMS | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(lv_tabview_get_tab_btns(ui_ScreenService_Tabview_Service), 255,  LV_PART_ITEMS| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(lv_tabview_get_tab_btns(ui_ScreenService_Tabview_Service), 1,  LV_PART_ITEMS| LV_STATE_DEFAULT);

ui_ScreenService_Tabpage_Warning = lv_tabview_add_tab(ui_ScreenService_Tabview_Service, "Warning");
lv_obj_clear_flag( ui_ScreenService_Tabpage_Warning, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_scrollbar_mode(ui_ScreenService_Tabpage_Warning, LV_SCROLLBAR_MODE_OFF);
lv_obj_set_scroll_dir(ui_ScreenService_Tabpage_Warning, LV_DIR_HOR);

ui_ScreenService_Roller_warnList = lv_roller_create(ui_ScreenService_Tabpage_Warning);
lv_obj_set_width( ui_ScreenService_Roller_warnList, 180);
lv_obj_set_height( ui_ScreenService_Roller_warnList, 158);
lv_obj_set_x( ui_ScreenService_Roller_warnList, -5 );
lv_obj_set_y( ui_ScreenService_Roller_warnList, -10 );
lv_obj_clear_flag( ui_ScreenService_Roller_warnList, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE );    /// Flags
lv_obj_set_scroll_dir(ui_ScreenService_Roller_warnList, LV_DIR_VER);
lv_obj_set_style_text_color(ui_ScreenService_Roller_warnList, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ScreenService_Roller_warnList, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_ScreenService_Roller_warnList, lv_color_hex(0x2C0101), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ScreenService_Roller_warnList, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_ScreenService_Roller_warnList, lv_color_hex(0x555555), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_ScreenService_Roller_warnList, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_ScreenService_Roller_warnList, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_ScreenService_Roller_warnList, lv_color_hex(0x222222), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_ScreenService_Roller_warnList, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_ScreenService_Roller_warnList, lv_color_hex(0xFF0000), LV_PART_SELECTED | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ScreenService_Roller_warnList, 255, LV_PART_SELECTED| LV_STATE_DEFAULT);

ui_ScreenService_Slider_limit = lv_slider_create(ui_ScreenService_Tabpage_Warning);
lv_slider_set_value( ui_ScreenService_Slider_limit, 0, LV_ANIM_OFF);
if (lv_slider_get_mode(ui_ScreenService_Slider_limit)==LV_SLIDER_MODE_RANGE ) lv_slider_set_left_value( ui_ScreenService_Slider_limit, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_ScreenService_Slider_limit, 20);
lv_obj_set_height( ui_ScreenService_Slider_limit, 150);
lv_obj_set_x( ui_ScreenService_Slider_limit, 220 );
lv_obj_set_y( ui_ScreenService_Slider_limit, 0 );
lv_obj_set_align( ui_ScreenService_Slider_limit, LV_ALIGN_LEFT_MID );
lv_obj_clear_flag( ui_ScreenService_Slider_limit, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE );    /// Flags
lv_obj_set_style_radius(ui_ScreenService_Slider_limit, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_ScreenService_Slider_limit, lv_color_hex(0x330000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ScreenService_Slider_limit, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_ScreenService_Slider_limit, lv_color_hex(0x555555), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_ScreenService_Slider_limit, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_width(ui_ScreenService_Slider_limit, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_pad(ui_ScreenService_Slider_limit, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_radius(ui_ScreenService_Slider_limit, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_ScreenService_Slider_limit, lv_color_hex(0xFF0000), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ScreenService_Slider_limit, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_radius(ui_ScreenService_Slider_limit, 5, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_ScreenService_Slider_limit, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ScreenService_Slider_limit, 255, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_dir(ui_ScreenService_Slider_limit, LV_GRAD_DIR_VER, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_ScreenService_Slider_limit, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_ScreenService_Slider_limit, 255, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_ScreenService_Slider_limit, 3, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_ScreenService_Label_min = lv_label_create(ui_ScreenService_Tabpage_Warning);
lv_obj_set_width( ui_ScreenService_Label_min, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ScreenService_Label_min, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ScreenService_Label_min, 226 );
lv_obj_set_y( ui_ScreenService_Label_min, 14 );
lv_obj_set_align( ui_ScreenService_Label_min, LV_ALIGN_BOTTOM_LEFT );
lv_label_set_text(ui_ScreenService_Label_min,"0");
lv_obj_set_style_text_color(ui_ScreenService_Label_min, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ScreenService_Label_min, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_ScreenService_Label_min, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ScreenService_Label_max = lv_label_create(ui_ScreenService_Tabpage_Warning);
lv_obj_set_width( ui_ScreenService_Label_max, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ScreenService_Label_max, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ScreenService_Label_max, 220 );
lv_obj_set_y( ui_ScreenService_Label_max, -15 );
lv_label_set_text(ui_ScreenService_Label_max,"100");
lv_obj_set_style_text_color(ui_ScreenService_Label_max, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ScreenService_Label_max, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_ScreenService_Label_max, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ScreenService_Button_saveWarn = lv_btn_create(ui_ScreenService_Tabpage_Warning);
lv_obj_set_width( ui_ScreenService_Button_saveWarn, 75);
lv_obj_set_height( ui_ScreenService_Button_saveWarn, 30);
lv_obj_set_x( ui_ScreenService_Button_saveWarn, -4 );
lv_obj_set_y( ui_ScreenService_Button_saveWarn, 3 );
lv_obj_set_align( ui_ScreenService_Button_saveWarn, LV_ALIGN_BOTTOM_LEFT );
lv_obj_add_flag( ui_ScreenService_Button_saveWarn, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ScreenService_Button_saveWarn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ScreenService_Button_saveWarn, lv_color_hex(0x00FF45), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ScreenService_Button_saveWarn, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_ScreenService_Button_saveWarn, lv_color_hex(0x013909), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_ScreenService_Button_saveWarn, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_ScreenService_Button_saveWarn, lv_color_hex(0x555555), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_ScreenService_Button_saveWarn, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_width(ui_ScreenService_Button_saveWarn, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_pad(ui_ScreenService_Button_saveWarn, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_ScreenService_Button_saveWarn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ScreenService_Button_saveWarn, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_ScreenService_Button_saveWarn, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ScreenService_Label_Save1 = lv_label_create(ui_ScreenService_Button_saveWarn);
lv_obj_set_width( ui_ScreenService_Label_Save1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ScreenService_Label_Save1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_ScreenService_Label_Save1, LV_ALIGN_CENTER );
lv_label_set_text(ui_ScreenService_Label_Save1,"SAVE");

ui_ScreenService_Button_setDefault = lv_btn_create(ui_ScreenService_Tabpage_Warning);
lv_obj_set_width( ui_ScreenService_Button_setDefault, 75);
lv_obj_set_height( ui_ScreenService_Button_setDefault, 30);
lv_obj_set_x( ui_ScreenService_Button_setDefault, 97 );
lv_obj_set_y( ui_ScreenService_Button_setDefault, 3 );
lv_obj_set_align( ui_ScreenService_Button_setDefault, LV_ALIGN_BOTTOM_LEFT );
lv_obj_add_flag( ui_ScreenService_Button_setDefault, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ScreenService_Button_setDefault, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ScreenService_Button_setDefault, lv_color_hex(0x0000FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ScreenService_Button_setDefault, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_ScreenService_Button_setDefault, lv_color_hex(0x020139), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_ScreenService_Button_setDefault, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_ScreenService_Button_setDefault, lv_color_hex(0x555555), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_ScreenService_Button_setDefault, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_width(ui_ScreenService_Button_setDefault, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_pad(ui_ScreenService_Button_setDefault, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_ScreenService_Button_setDefault, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ScreenService_Button_setDefault, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_ScreenService_Button_setDefault, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ScreenService_Label_Save2 = lv_label_create(ui_ScreenService_Button_setDefault);
lv_obj_set_width( ui_ScreenService_Label_Save2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ScreenService_Label_Save2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_ScreenService_Label_Save2, LV_ALIGN_CENTER );
lv_label_set_text(ui_ScreenService_Label_Save2,"Default");

ui_ScreenService_Label_warnValue = lv_label_create(ui_ScreenService_Tabpage_Warning);
lv_obj_set_width( ui_ScreenService_Label_warnValue, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ScreenService_Label_warnValue, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ScreenService_Label_warnValue, 255 );
lv_obj_set_y( ui_ScreenService_Label_warnValue, 0 );
lv_obj_set_align( ui_ScreenService_Label_warnValue, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_ScreenService_Label_warnValue,"50");
lv_obj_set_style_text_color(ui_ScreenService_Label_warnValue, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ScreenService_Label_warnValue, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_ScreenService_Label_warnValue, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ScreenService_Tabpage_Diagnostics = lv_tabview_add_tab(ui_ScreenService_Tabview_Service, "     Diagnostics");
lv_obj_clear_flag( ui_ScreenService_Tabpage_Diagnostics, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_scrollbar_mode(ui_ScreenService_Tabpage_Diagnostics, LV_SCROLLBAR_MODE_OFF);
lv_obj_set_scroll_dir(ui_ScreenService_Tabpage_Diagnostics, LV_DIR_HOR);

ui_ScreenService_Button_readDTC = lv_btn_create(ui_ScreenService_Tabpage_Diagnostics);
lv_obj_set_height( ui_ScreenService_Button_readDTC, 50);
lv_obj_set_width( ui_ScreenService_Button_readDTC, LV_SIZE_CONTENT);  /// 100
lv_obj_set_x( ui_ScreenService_Button_readDTC, -80 );
lv_obj_set_y( ui_ScreenService_Button_readDTC, 25 );
lv_obj_set_align( ui_ScreenService_Button_readDTC, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ScreenService_Button_readDTC, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ScreenService_Button_readDTC, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ScreenService_Button_readDTC, lv_color_hex(0x0000FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ScreenService_Button_readDTC, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_ScreenService_Button_readDTC, lv_color_hex(0x06014C), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_ScreenService_Button_readDTC, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_ScreenService_Button_readDTC, lv_color_hex(0x555555), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_ScreenService_Button_readDTC, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_width(ui_ScreenService_Button_readDTC, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_pad(ui_ScreenService_Button_readDTC, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_ScreenService_Button_readDTC, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_ScreenService_Button_readDTC, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_ScreenService_Button_readDTC, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ScreenService_Label_Label5 = lv_label_create(ui_ScreenService_Button_readDTC);
lv_obj_set_width( ui_ScreenService_Label_Label5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ScreenService_Label_Label5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_ScreenService_Label_Label5, LV_ALIGN_CENTER );
lv_label_set_text(ui_ScreenService_Label_Label5,"Diagnostics");

ui_ScreenService_Button_updateDescription = lv_btn_create(ui_ScreenService_Tabpage_Diagnostics);
lv_obj_set_height( ui_ScreenService_Button_updateDescription, 50);
lv_obj_set_width( ui_ScreenService_Button_updateDescription, LV_SIZE_CONTENT);  /// 100
lv_obj_set_x( ui_ScreenService_Button_updateDescription, 80 );
lv_obj_set_y( ui_ScreenService_Button_updateDescription, 25 );
lv_obj_set_align( ui_ScreenService_Button_updateDescription, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ScreenService_Button_updateDescription, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ScreenService_Button_updateDescription, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ScreenService_Button_updateDescription, lv_color_hex(0xED00FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ScreenService_Button_updateDescription, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_ScreenService_Button_updateDescription, lv_color_hex(0x47014C), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_ScreenService_Button_updateDescription, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_ScreenService_Button_updateDescription, lv_color_hex(0x555555), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_ScreenService_Button_updateDescription, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_width(ui_ScreenService_Button_updateDescription, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_pad(ui_ScreenService_Button_updateDescription, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_ScreenService_Button_updateDescription, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_ScreenService_Button_updateDescription, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_ScreenService_Button_updateDescription, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ScreenService_Label_Label10 = lv_label_create(ui_ScreenService_Button_updateDescription);
lv_obj_set_width( ui_ScreenService_Label_Label10, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ScreenService_Label_Label10, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_ScreenService_Label_Label10, LV_ALIGN_BOTTOM_MID );
lv_label_set_text(ui_ScreenService_Label_Label10,"Update\nDescription");
lv_obj_set_style_text_align(ui_ScreenService_Label_Label10, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ScreenService_Label_pleasewait = lv_label_create(ui_ScreenService_Tabpage_Diagnostics);
lv_obj_set_width( ui_ScreenService_Label_pleasewait, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ScreenService_Label_pleasewait, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ScreenService_Label_pleasewait, 0 );
lv_obj_set_y( ui_ScreenService_Label_pleasewait, -50 );
lv_obj_set_align( ui_ScreenService_Label_pleasewait, LV_ALIGN_CENTER );
lv_label_set_text(ui_ScreenService_Label_pleasewait,"Touch to start diagnostics (Read DTCs)");
lv_obj_set_style_text_color(ui_ScreenService_Label_pleasewait, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ScreenService_Label_pleasewait, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_ScreenService_Label_pleasewait, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ScreenService_Panel_dtc = lv_obj_create(ui_ScreenService_Tabpage_Diagnostics);
lv_obj_set_width( ui_ScreenService_Panel_dtc, lv_pct(100));
lv_obj_set_height( ui_ScreenService_Panel_dtc, lv_pct(110));
lv_obj_set_align( ui_ScreenService_Panel_dtc, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ScreenService_Panel_dtc, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_clear_flag( ui_ScreenService_Panel_dtc, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ScreenService_Panel_dtc, lv_color_hex(0x333333), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ScreenService_Panel_dtc, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_ScreenService_Panel_dtc, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_ScreenService_Panel_dtc, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ScreenService_Button_clearMIL = lv_btn_create(ui_ScreenService_Panel_dtc);
lv_obj_set_width( ui_ScreenService_Button_clearMIL, 90);
lv_obj_set_height( ui_ScreenService_Button_clearMIL, 32);
lv_obj_set_x( ui_ScreenService_Button_clearMIL, -10 );
lv_obj_set_y( ui_ScreenService_Button_clearMIL, 3 );
lv_obj_set_align( ui_ScreenService_Button_clearMIL, LV_ALIGN_BOTTOM_RIGHT );
lv_obj_add_flag( ui_ScreenService_Button_clearMIL, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ScreenService_Button_clearMIL, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ScreenService_Button_clearMIL, lv_color_hex(0xFBFB01), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ScreenService_Button_clearMIL, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_ScreenService_Button_clearMIL, lv_color_hex(0x424901), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_ScreenService_Button_clearMIL, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_ScreenService_Button_clearMIL, lv_color_hex(0x555555), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_ScreenService_Button_clearMIL, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_width(ui_ScreenService_Button_clearMIL, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_pad(ui_ScreenService_Button_clearMIL, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_ScreenService_Button_clearMIL, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_ScreenService_Button_clearMIL, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_ScreenService_Button_clearMIL, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ScreenService_Button_clearMIL, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_ScreenService_Button_clearMIL, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ScreenService_Label_Label7 = lv_label_create(ui_ScreenService_Button_clearMIL);
lv_obj_set_width( ui_ScreenService_Label_Label7, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ScreenService_Label_Label7, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_ScreenService_Label_Label7, LV_ALIGN_CENTER );
lv_label_set_text(ui_ScreenService_Label_Label7,"Clear MIL");

ui_ScreenService_Textarea_DTCList = lv_textarea_create(ui_ScreenService_Panel_dtc);
lv_obj_set_width( ui_ScreenService_Textarea_DTCList, lv_pct(100));
lv_obj_set_height( ui_ScreenService_Textarea_DTCList, lv_pct(72));
lv_obj_set_x( ui_ScreenService_Textarea_DTCList, 0 );
lv_obj_set_y( ui_ScreenService_Textarea_DTCList, -13 );
lv_obj_set_align( ui_ScreenService_Textarea_DTCList, LV_ALIGN_CENTER );
lv_textarea_set_placeholder_text(ui_ScreenService_Textarea_DTCList,"DTCs will appear here");
lv_obj_clear_flag( ui_ScreenService_Textarea_DTCList, LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM );    /// Flags
lv_obj_set_scroll_dir(ui_ScreenService_Textarea_DTCList, LV_DIR_VER);
lv_obj_set_style_text_color(ui_ScreenService_Textarea_DTCList, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ScreenService_Textarea_DTCList, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_letter_space(ui_ScreenService_Textarea_DTCList, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_ScreenService_Textarea_DTCList, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_ScreenService_Textarea_DTCList, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_ScreenService_Textarea_DTCList, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ScreenService_Textarea_DTCList, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_ScreenService_Textarea_DTCList, lv_color_hex(0x555555), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_ScreenService_Textarea_DTCList, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_ScreenService_Textarea_DTCList, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ScreenService_Label_MILStatus = lv_label_create(ui_ScreenService_Panel_dtc);
lv_obj_set_width( ui_ScreenService_Label_MILStatus, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ScreenService_Label_MILStatus, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ScreenService_Label_MILStatus, 0 );
lv_obj_set_y( ui_ScreenService_Label_MILStatus, -10 );
lv_obj_set_align( ui_ScreenService_Label_MILStatus, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_ScreenService_Label_MILStatus,"");
lv_obj_set_style_text_color(ui_ScreenService_Label_MILStatus, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ScreenService_Label_MILStatus, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ScreenService_Button_closeDTC = lv_btn_create(ui_ScreenService_Panel_dtc);
lv_obj_set_width( ui_ScreenService_Button_closeDTC, 90);
lv_obj_set_height( ui_ScreenService_Button_closeDTC, 32);
lv_obj_set_x( ui_ScreenService_Button_closeDTC, 10 );
lv_obj_set_y( ui_ScreenService_Button_closeDTC, 4 );
lv_obj_set_align( ui_ScreenService_Button_closeDTC, LV_ALIGN_BOTTOM_LEFT );
lv_obj_add_flag( ui_ScreenService_Button_closeDTC, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ScreenService_Button_closeDTC, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ScreenService_Button_closeDTC, lv_color_hex(0x01BEFB), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ScreenService_Button_closeDTC, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_ScreenService_Button_closeDTC, lv_color_hex(0x013F49), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_ScreenService_Button_closeDTC, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_ScreenService_Button_closeDTC, lv_color_hex(0x555555), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_ScreenService_Button_closeDTC, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_width(ui_ScreenService_Button_closeDTC, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_pad(ui_ScreenService_Button_closeDTC, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_ScreenService_Button_closeDTC, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_ScreenService_Button_closeDTC, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_ScreenService_Button_closeDTC, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ScreenService_Button_closeDTC, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_ScreenService_Button_closeDTC, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ScreenService_Label_Label8 = lv_label_create(ui_ScreenService_Button_closeDTC);
lv_obj_set_width( ui_ScreenService_Label_Label8, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ScreenService_Label_Label8, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_ScreenService_Label_Label8, LV_ALIGN_CENTER );
lv_label_set_text(ui_ScreenService_Label_Label8,"Close");

ui_ScreenService_Image_Image1 = lv_img_create(ui_Screen_ScreenService);
lv_img_set_src(ui_ScreenService_Image_Image1, &ui_img_mil_png);
lv_obj_set_width( ui_ScreenService_Image_Image1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ScreenService_Image_Image1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ScreenService_Image_Image1, 22 );
lv_obj_set_y( ui_ScreenService_Image_Image1, 104 );
lv_obj_set_align( ui_ScreenService_Image_Image1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ScreenService_Image_Image1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ScreenService_Image_Image1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_ScreenService_Image_Image2 = lv_img_create(ui_Screen_ScreenService);
lv_img_set_src(ui_ScreenService_Image_Image2, &ui_img_alert_png);
lv_obj_set_width( ui_ScreenService_Image_Image2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ScreenService_Image_Image2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ScreenService_Image_Image2, -138 );
lv_obj_set_y( ui_ScreenService_Image_Image2, 102 );
lv_obj_set_align( ui_ScreenService_Image_Image2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ScreenService_Image_Image2, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ScreenService_Image_Image2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_ScreenService_Button_swipeUp = lv_btn_create(ui_Screen_ScreenService);
lv_obj_set_width( ui_ScreenService_Button_swipeUp, 36);
lv_obj_set_height( ui_ScreenService_Button_swipeUp, 36);
lv_obj_set_align( ui_ScreenService_Button_swipeUp, LV_ALIGN_TOP_RIGHT );
lv_obj_add_flag( ui_ScreenService_Button_swipeUp, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ScreenService_Button_swipeUp, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ScreenService_Button_swipeUp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ScreenService_Button_swipeUp, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_ScreenService_Button_swipeUp, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_ScreenService_Button_swipeUp, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ScreenService_Label_upup = lv_label_create(ui_ScreenService_Button_swipeUp);
lv_obj_set_width( ui_ScreenService_Label_upup, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ScreenService_Label_upup, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_ScreenService_Label_upup, LV_ALIGN_CENTER );
lv_label_set_text(ui_ScreenService_Label_upup,"^");
lv_obj_set_style_text_color(ui_ScreenService_Label_upup, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ScreenService_Label_upup, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_ScreenService_Label_upup, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_ScreenService_Label_upup, &lv_font_montserrat_38, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_ScreenService_Roller_warnList, ui_event_ScreenService_Roller_warnList, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ScreenService_Slider_limit, ui_event_ScreenService_Slider_limit, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ScreenService_Button_readDTC, ui_event_ScreenService_Button_readDTC, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ScreenService_Button_updateDescription, ui_event_ScreenService_Button_updateDescription, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ScreenService_Button_clearMIL, ui_event_ScreenService_Button_clearMIL, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ScreenService_Button_closeDTC, ui_event_ScreenService_Button_closeDTC, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ScreenService_Tabview_Service, ui_event_ScreenService_Tabview_Service, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ScreenService_Button_swipeUp, ui_event_ScreenService_Button_swipeUp, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Screen_ScreenService, ui_event_Screen_ScreenService, LV_EVENT_ALL, NULL);

}

void ui_Screen_ScreenService_screen_destroy(void)
{
   if (ui_Screen_ScreenService) lv_obj_del(ui_Screen_ScreenService);

// NULL screen variables
ui_Screen_ScreenService= NULL;
ui_ScreenService_Tabview_Service= NULL;
ui_ScreenService_Tabpage_Warning= NULL;
ui_ScreenService_Roller_warnList= NULL;
ui_ScreenService_Slider_limit= NULL;
ui_ScreenService_Label_min= NULL;
ui_ScreenService_Label_max= NULL;
ui_ScreenService_Button_saveWarn= NULL;
ui_ScreenService_Label_Save1= NULL;
ui_ScreenService_Button_setDefault= NULL;
ui_ScreenService_Label_Save2= NULL;
ui_ScreenService_Label_warnValue= NULL;
ui_ScreenService_Tabpage_Diagnostics= NULL;
ui_ScreenService_Button_readDTC= NULL;
ui_ScreenService_Label_Label5= NULL;
ui_ScreenService_Button_updateDescription= NULL;
ui_ScreenService_Label_Label10= NULL;
ui_ScreenService_Label_pleasewait= NULL;
ui_ScreenService_Panel_dtc= NULL;
ui_ScreenService_Button_clearMIL= NULL;
ui_ScreenService_Label_Label7= NULL;
ui_ScreenService_Textarea_DTCList= NULL;
ui_ScreenService_Label_MILStatus= NULL;
ui_ScreenService_Button_closeDTC= NULL;
ui_ScreenService_Label_Label8= NULL;
ui_ScreenService_Image_Image1= NULL;
ui_ScreenService_Image_Image2= NULL;
ui_ScreenService_Button_swipeUp= NULL;
ui_ScreenService_Label_upup= NULL;

}
