// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: obd2_gauge_catalyst

#include "ui.h"

lv_obj_t *ui_Screen_ScreenPerformance = NULL;lv_obj_t *ui_ScreenPerformance_Chart_top = NULL;lv_obj_t *ui_ScreenPerformance_Label_series1left = NULL;lv_obj_t *ui_ScreenPerformance_Label_series1right = NULL;lv_obj_t *ui_ScreenPerformance_Label_chart1X = NULL;lv_obj_t *ui_ScreenPerformance_Chart_bottom = NULL;lv_obj_t *ui_ScreenPerformance_Label_series2left = NULL;lv_obj_t *ui_ScreenPerformance_Label_series2right = NULL;lv_obj_t *ui_ScreenPerformance_Label_chart2X = NULL;lv_obj_t *ui_ScreenPerformance_Button_swipeRight = NULL;lv_obj_t *ui_ScreenPerformance_Label_right = NULL;lv_obj_t *ui_ScreenPerformance_Label_info3 = NULL;
// event funtions
void ui_event_Screen_ScreenPerformance( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT  ) {
lv_indev_wait_release(lv_indev_get_act());
      changeScreenGauge( e );
      _ui_screen_change( &ui_Screen_ScreenGauge, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_Screen_ScreenGauge_screen_init);
}
}

void ui_event_ScreenPerformance_Chart_top( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      togglePointChart1( e );
}
}

void ui_event_ScreenPerformance_Chart_bottom( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      togglePointChart2( e );
}
}

void ui_event_ScreenPerformance_Button_swipeRight( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Screen_ScreenGauge, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_Screen_ScreenGauge_screen_init);
      changeScreenGauge( e );
}
}

// build funtions

void ui_Screen_ScreenPerformance_screen_init(void)
{
ui_Screen_ScreenPerformance = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen_ScreenPerformance, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Screen_ScreenPerformance, lv_color_hex(0x333333), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Screen_ScreenPerformance, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_Screen_ScreenPerformance, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_Screen_ScreenPerformance, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_Screen_ScreenPerformance, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Screen_ScreenPerformance, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_Screen_ScreenPerformance, lv_color_hex(0x333333), LV_PART_SCROLLBAR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Screen_ScreenPerformance, 255, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_Screen_ScreenPerformance, lv_color_hex(0x000000), LV_PART_SCROLLBAR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_Screen_ScreenPerformance, LV_GRAD_DIR_VER, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);

ui_ScreenPerformance_Chart_top = lv_chart_create(ui_Screen_ScreenPerformance);
lv_obj_set_width( ui_ScreenPerformance_Chart_top, 240);
lv_obj_set_height( ui_ScreenPerformance_Chart_top, 115);
lv_obj_set_align( ui_ScreenPerformance_Chart_top, LV_ALIGN_TOP_MID );
lv_chart_set_type( ui_ScreenPerformance_Chart_top, LV_CHART_TYPE_LINE);
lv_chart_set_point_count( ui_ScreenPerformance_Chart_top, 60);
lv_chart_set_range( ui_ScreenPerformance_Chart_top, LV_CHART_AXIS_PRIMARY_Y, 0, 0);
lv_chart_set_range( ui_ScreenPerformance_Chart_top, LV_CHART_AXIS_SECONDARY_Y, 0, 0);
lv_chart_set_div_line_count( ui_ScreenPerformance_Chart_top, 5, 7);
lv_chart_set_axis_tick( ui_ScreenPerformance_Chart_top, LV_CHART_AXIS_PRIMARY_X, 0, 0, 0, 0, true, 0);
lv_chart_set_axis_tick( ui_ScreenPerformance_Chart_top, LV_CHART_AXIS_PRIMARY_Y, 7, 4, 5, 1, true, 40);
lv_chart_set_axis_tick( ui_ScreenPerformance_Chart_top, LV_CHART_AXIS_SECONDARY_Y, 7, 4, 5, 1, true, 40);
lv_obj_set_style_radius(ui_ScreenPerformance_Chart_top, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_ScreenPerformance_Chart_top, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ScreenPerformance_Chart_top, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_ScreenPerformance_Chart_top, lv_color_hex(0x7F0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_main_stop(ui_ScreenPerformance_Chart_top, 200, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_stop(ui_ScreenPerformance_Chart_top, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_dir(ui_ScreenPerformance_Chart_top, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_ScreenPerformance_Chart_top, lv_color_hex(0x880000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_ScreenPerformance_Chart_top, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_ScreenPerformance_Chart_top, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_ScreenPerformance_Chart_top, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_width(ui_ScreenPerformance_Chart_top, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_pad(ui_ScreenPerformance_Chart_top, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_line_color(ui_ScreenPerformance_Chart_top, lv_color_hex(0x444444), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_line_opa(ui_ScreenPerformance_Chart_top, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_line_width(ui_ScreenPerformance_Chart_top, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_size(ui_ScreenPerformance_Chart_top, 1, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_line_color(ui_ScreenPerformance_Chart_top, lv_color_hex(0xBBBBBB), LV_PART_TICKS | LV_STATE_DEFAULT );
lv_obj_set_style_line_opa(ui_ScreenPerformance_Chart_top, 255, LV_PART_TICKS| LV_STATE_DEFAULT);
lv_obj_set_style_line_width(ui_ScreenPerformance_Chart_top, 2, LV_PART_TICKS| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_ScreenPerformance_Chart_top, lv_color_hex(0xBBBBBB), LV_PART_TICKS | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ScreenPerformance_Chart_top, 255, LV_PART_TICKS| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_ScreenPerformance_Chart_top, LV_TEXT_ALIGN_CENTER, LV_PART_TICKS| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_ScreenPerformance_Chart_top, &lv_font_montserrat_14, LV_PART_TICKS| LV_STATE_DEFAULT);

ui_ScreenPerformance_Label_series1left = lv_label_create(ui_ScreenPerformance_Chart_top);
lv_obj_set_width( ui_ScreenPerformance_Label_series1left, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ScreenPerformance_Label_series1left, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ScreenPerformance_Label_series1left, 0 );
lv_obj_set_y( ui_ScreenPerformance_Label_series1left, -5 );
lv_label_set_text(ui_ScreenPerformance_Label_series1left,"-");
lv_obj_set_style_text_color(ui_ScreenPerformance_Label_series1left, lv_color_hex(0xF000F0), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ScreenPerformance_Label_series1left, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_ScreenPerformance_Label_series1left, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ScreenPerformance_Label_series1right = lv_label_create(ui_ScreenPerformance_Chart_top);
lv_obj_set_width( ui_ScreenPerformance_Label_series1right, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ScreenPerformance_Label_series1right, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ScreenPerformance_Label_series1right, 0 );
lv_obj_set_y( ui_ScreenPerformance_Label_series1right, -5 );
lv_obj_set_align( ui_ScreenPerformance_Label_series1right, LV_ALIGN_TOP_RIGHT );
lv_label_set_text(ui_ScreenPerformance_Label_series1right,"-");
lv_obj_set_style_text_color(ui_ScreenPerformance_Label_series1right, lv_color_hex(0xF0F000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ScreenPerformance_Label_series1right, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_ScreenPerformance_Label_series1right, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ScreenPerformance_Label_chart1X = lv_label_create(ui_ScreenPerformance_Chart_top);
lv_obj_set_width( ui_ScreenPerformance_Label_chart1X, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ScreenPerformance_Label_chart1X, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ScreenPerformance_Label_chart1X, 0 );
lv_obj_set_y( ui_ScreenPerformance_Label_chart1X, -5 );
lv_obj_set_align( ui_ScreenPerformance_Label_chart1X, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_ScreenPerformance_Label_chart1X,"1x");
lv_obj_set_style_text_color(ui_ScreenPerformance_Label_chart1X, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ScreenPerformance_Label_chart1X, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_ScreenPerformance_Label_chart1X, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ScreenPerformance_Chart_bottom = lv_chart_create(ui_Screen_ScreenPerformance);
lv_obj_set_width( ui_ScreenPerformance_Chart_bottom, 240);
lv_obj_set_height( ui_ScreenPerformance_Chart_bottom, 115);
lv_obj_set_align( ui_ScreenPerformance_Chart_bottom, LV_ALIGN_BOTTOM_MID );
lv_chart_set_type( ui_ScreenPerformance_Chart_bottom, LV_CHART_TYPE_LINE);
lv_chart_set_point_count( ui_ScreenPerformance_Chart_bottom, 60);
lv_chart_set_range( ui_ScreenPerformance_Chart_bottom, LV_CHART_AXIS_PRIMARY_Y, 0, 0);
lv_chart_set_range( ui_ScreenPerformance_Chart_bottom, LV_CHART_AXIS_SECONDARY_Y, 0, 0);
lv_chart_set_div_line_count( ui_ScreenPerformance_Chart_bottom, 5, 7);
lv_chart_set_axis_tick( ui_ScreenPerformance_Chart_bottom, LV_CHART_AXIS_PRIMARY_X, 0, 0, 0, 0, true, 0);
lv_chart_set_axis_tick( ui_ScreenPerformance_Chart_bottom, LV_CHART_AXIS_PRIMARY_Y, 7, 4, 5, 1, true, 40);
lv_chart_set_axis_tick( ui_ScreenPerformance_Chart_bottom, LV_CHART_AXIS_SECONDARY_Y, 7, 4, 5, 1, true, 0);
lv_obj_set_style_radius(ui_ScreenPerformance_Chart_bottom, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_ScreenPerformance_Chart_bottom, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ScreenPerformance_Chart_bottom, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_ScreenPerformance_Chart_bottom, lv_color_hex(0x700000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_main_stop(ui_ScreenPerformance_Chart_bottom, 200, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_stop(ui_ScreenPerformance_Chart_bottom, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_dir(ui_ScreenPerformance_Chart_bottom, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_ScreenPerformance_Chart_bottom, lv_color_hex(0x880000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_ScreenPerformance_Chart_bottom, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_ScreenPerformance_Chart_bottom, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_ScreenPerformance_Chart_bottom, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_width(ui_ScreenPerformance_Chart_bottom, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_pad(ui_ScreenPerformance_Chart_bottom, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_line_color(ui_ScreenPerformance_Chart_bottom, lv_color_hex(0x444444), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_line_opa(ui_ScreenPerformance_Chart_bottom, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_line_width(ui_ScreenPerformance_Chart_bottom, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_size(ui_ScreenPerformance_Chart_bottom, 1, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_line_color(ui_ScreenPerformance_Chart_bottom, lv_color_hex(0xBBBBBB), LV_PART_TICKS | LV_STATE_DEFAULT );
lv_obj_set_style_line_opa(ui_ScreenPerformance_Chart_bottom, 255, LV_PART_TICKS| LV_STATE_DEFAULT);
lv_obj_set_style_line_width(ui_ScreenPerformance_Chart_bottom, 2, LV_PART_TICKS| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_ScreenPerformance_Chart_bottom, lv_color_hex(0xBBBBBB), LV_PART_TICKS | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ScreenPerformance_Chart_bottom, 255, LV_PART_TICKS| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_ScreenPerformance_Chart_bottom, LV_TEXT_ALIGN_CENTER, LV_PART_TICKS| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_ScreenPerformance_Chart_bottom, &lv_font_montserrat_14, LV_PART_TICKS| LV_STATE_DEFAULT);

ui_ScreenPerformance_Label_series2left = lv_label_create(ui_ScreenPerformance_Chart_bottom);
lv_obj_set_width( ui_ScreenPerformance_Label_series2left, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ScreenPerformance_Label_series2left, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ScreenPerformance_Label_series2left, 0 );
lv_obj_set_y( ui_ScreenPerformance_Label_series2left, -5 );
lv_label_set_text(ui_ScreenPerformance_Label_series2left,"-");
lv_obj_set_style_text_color(ui_ScreenPerformance_Label_series2left, lv_color_hex(0x00F0F0), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ScreenPerformance_Label_series2left, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_ScreenPerformance_Label_series2left, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ScreenPerformance_Label_series2right = lv_label_create(ui_ScreenPerformance_Chart_bottom);
lv_obj_set_width( ui_ScreenPerformance_Label_series2right, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ScreenPerformance_Label_series2right, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ScreenPerformance_Label_series2right, 0 );
lv_obj_set_y( ui_ScreenPerformance_Label_series2right, -5 );
lv_obj_set_align( ui_ScreenPerformance_Label_series2right, LV_ALIGN_TOP_RIGHT );
lv_label_set_text(ui_ScreenPerformance_Label_series2right,"-");
lv_obj_set_style_text_color(ui_ScreenPerformance_Label_series2right, lv_color_hex(0xFEA139), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ScreenPerformance_Label_series2right, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_ScreenPerformance_Label_series2right, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ScreenPerformance_Label_chart2X = lv_label_create(ui_ScreenPerformance_Chart_bottom);
lv_obj_set_width( ui_ScreenPerformance_Label_chart2X, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ScreenPerformance_Label_chart2X, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ScreenPerformance_Label_chart2X, 0 );
lv_obj_set_y( ui_ScreenPerformance_Label_chart2X, -5 );
lv_obj_set_align( ui_ScreenPerformance_Label_chart2X, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_ScreenPerformance_Label_chart2X,"1x");
lv_obj_set_style_text_color(ui_ScreenPerformance_Label_chart2X, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ScreenPerformance_Label_chart2X, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_ScreenPerformance_Label_chart2X, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ScreenPerformance_Button_swipeRight = lv_btn_create(ui_Screen_ScreenPerformance);
lv_obj_set_width( ui_ScreenPerformance_Button_swipeRight, 36);
lv_obj_set_height( ui_ScreenPerformance_Button_swipeRight, 36);
lv_obj_set_align( ui_ScreenPerformance_Button_swipeRight, LV_ALIGN_RIGHT_MID );
lv_obj_add_flag( ui_ScreenPerformance_Button_swipeRight, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ScreenPerformance_Button_swipeRight, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ScreenPerformance_Button_swipeRight, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ScreenPerformance_Button_swipeRight, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_ScreenPerformance_Button_swipeRight, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_ScreenPerformance_Button_swipeRight, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ScreenPerformance_Label_right = lv_label_create(ui_ScreenPerformance_Button_swipeRight);
lv_obj_set_width( ui_ScreenPerformance_Label_right, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ScreenPerformance_Label_right, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_ScreenPerformance_Label_right, LV_ALIGN_CENTER );
lv_label_set_text(ui_ScreenPerformance_Label_right,">");
lv_obj_set_style_text_color(ui_ScreenPerformance_Label_right, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ScreenPerformance_Label_right, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_ScreenPerformance_Label_right, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_ScreenPerformance_Label_right, &lv_font_montserrat_38, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ScreenPerformance_Label_info3 = lv_label_create(ui_Screen_ScreenPerformance);
lv_obj_set_width( ui_ScreenPerformance_Label_info3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ScreenPerformance_Label_info3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_ScreenPerformance_Label_info3, LV_ALIGN_CENTER );
lv_label_set_text(ui_ScreenPerformance_Label_info3,"");
lv_obj_set_style_text_color(ui_ScreenPerformance_Label_info3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ScreenPerformance_Label_info3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_ScreenPerformance_Label_info3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_ScreenPerformance_Label_info3, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_ScreenPerformance_Label_info3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ScreenPerformance_Label_info3, 127, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_ScreenPerformance_Chart_top, ui_event_ScreenPerformance_Chart_top, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ScreenPerformance_Chart_bottom, ui_event_ScreenPerformance_Chart_bottom, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ScreenPerformance_Button_swipeRight, ui_event_ScreenPerformance_Button_swipeRight, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Screen_ScreenPerformance, ui_event_Screen_ScreenPerformance, LV_EVENT_ALL, NULL);

}

void ui_Screen_ScreenPerformance_screen_destroy(void)
{
   if (ui_Screen_ScreenPerformance) lv_obj_del(ui_Screen_ScreenPerformance);

// NULL screen variables
ui_Screen_ScreenPerformance= NULL;
ui_ScreenPerformance_Chart_top= NULL;
ui_ScreenPerformance_Label_series1left= NULL;
ui_ScreenPerformance_Label_series1right= NULL;
ui_ScreenPerformance_Label_chart1X= NULL;
ui_ScreenPerformance_Chart_bottom= NULL;
ui_ScreenPerformance_Label_series2left= NULL;
ui_ScreenPerformance_Label_series2right= NULL;
ui_ScreenPerformance_Label_chart2X= NULL;
ui_ScreenPerformance_Button_swipeRight= NULL;
ui_ScreenPerformance_Label_right= NULL;
ui_ScreenPerformance_Label_info3= NULL;

}
